const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Orbit,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.JavaScriptInEvents.Gameevent_Event19_Act21,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.StopTimelineByTags,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.CompareX,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Orbit: 0},
	{Tween: 0},
	{block: 0},
	{block10: 0},
	{block11: 0},
	{block11two: 0},
	{Rotate: 0},
	{block12: 0},
	{block12two: 0},
	{block13: 0},
	{Bullet: 0},
	{block14: 0},
	{block15: 0},
	{block16: 0},
	{block17: 0},
	{Sine: 0},
	{block18: 0},
	{block2: 0},
	{block3: 0},
	{block4: 0},
	{block5: 0},
	{block6: 0},
	{block7: 0},
	{block7two: 0},
	{block8: 0},
	{block9: 0},
	{block9two: 0},
	{boardLevel: 0},
	{destroyPick: 0},
	{DestroyOutsideLayout: 0},
	{bulletBall: 0},
	{destroyEnemyParticle: 0},
	{destroyEnemyParticleYellow: 0},
	{life: 0},
	{enemy: 0},
	{enemyEffect: 0},
	{homeButton: 0},
	{lifeOff: 0},
	{lifenumber: 0},
	{lifeOn: 0},
	{Particles: 0},
	{place: 0},
	{player: 0},
	{Pin: 0},
	{triggerBlock8: 0},
	{Sine2: 0},
	{triggerLevel28: 0},
	{Fade: 0},
	{fadeOver: 0},
	{place1: 0},
	{place2: 0},
	{plant: 0},
	{MENU: 0},
	{MENUBOLL: 0},
	{dot: 0},
	{level: 0},
	{levelCircle: 0},
	{returnButton: 0},
	{Background: 0},
	{start: 0},
	{titleMenu: 0},
	{levelNumber: 0},
	{levelText: 0},
	{Logo1: 0},
	{Logo2: 0},
	{pointText: 0},
	{tutorialText: 0},
	{Touch: 0},
	{Timeline: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Sprite: 0},
	{Video: 0},
	{logoGl: 0},
	{Browser: 0},
	{AJAX: 0},
	{JSON: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{blocks: 0},
	{CompletedLevels: 0},
	{Levels: 0},
	{Point: 0}
];

self.InstanceType = {
	block: class extends self.ISpriteInstance {},
	block10: class extends self.ISpriteInstance {},
	block11: class extends self.ISpriteInstance {},
	block11two: class extends self.ISpriteInstance {},
	block12: class extends self.ISpriteInstance {},
	block12two: class extends self.ISpriteInstance {},
	block13: class extends self.ISpriteInstance {},
	block14: class extends self.ISpriteInstance {},
	block15: class extends self.ISpriteInstance {},
	block16: class extends self.ISpriteInstance {},
	block17: class extends self.ISpriteInstance {},
	block18: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	block3: class extends self.ISpriteInstance {},
	block4: class extends self.ISpriteInstance {},
	block5: class extends self.ISpriteInstance {},
	block6: class extends self.ISpriteInstance {},
	block7: class extends self.ISpriteInstance {},
	block7two: class extends self.ISpriteInstance {},
	block8: class extends self.ISpriteInstance {},
	block9: class extends self.ISpriteInstance {},
	block9two: class extends self.ISpriteInstance {},
	boardLevel: class extends self.ISpriteInstance {},
	bulletBall: class extends self.ISpriteInstance {},
	destroyEnemyParticle: class extends self.IParticlesInstance {},
	destroyEnemyParticleYellow: class extends self.IParticlesInstance {},
	enemy: class extends self.ISpriteInstance {},
	enemyEffect: class extends self.ISpriteInstance {},
	homeButton: class extends self.ISpriteInstance {},
	lifeOff: class extends self.ISpriteInstance {},
	lifeOn: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	place: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	triggerBlock8: class extends self.ISpriteInstance {},
	triggerLevel28: class extends self.ISpriteInstance {},
	fadeOver: class extends self.ITiledBackgroundInstance {},
	place1: class extends self.ISpriteInstance {},
	place2: class extends self.ISpriteInstance {},
	plant: class extends self.ISpriteInstance {},
	MENU: class extends self.ISpriteInstance {},
	MENUBOLL: class extends self.ISpriteInstance {},
	dot: class extends self.ISpriteInstance {},
	levelCircle: class extends self.ISpriteInstance {},
	returnButton: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	start: class extends self.ISpriteInstance {},
	titleMenu: class extends self.ISpriteInstance {},
	levelNumber: class extends self.ITextInstance {},
	levelText: class extends self.ITextInstance {},
	Logo1: class extends self.ITextInstance {},
	Logo2: class extends self.ITextInstance {},
	pointText: class extends self.ITextInstance {},
	tutorialText: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Timeline: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	logoGl: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	blocks: class extends self.ISpriteInstance {}
}