const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.EventGameplay_Event24_Act2,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.EventGameplay_Event38_Act8,
		C3.JavaScriptInEvents.EventMenu_Event2_Act2,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{var_angle: 0},
	{Fade: 0},
	{ColorMove: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Sine: 0},
	{ColorPlayer: 0},
	{TextScore: 0},
	{EffectMove: 0},
	{Particles: 0},
	{Logo: 0},
	{InfoBest: 0},
	{InfoScore: 0},
	{TextBest: 0},
	{game_bg: 0},
	{menu_bg: 0},
	{Keyboard: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Pin: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{var_score: 0},
	{var_score_best: 0},
	{var_color: 0},
	{var_difficulty: 0},
	{var_position: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0}
];

self.InstanceType = {
	ColorMove: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	ColorPlayer: class extends self.ISpriteInstance {},
	TextScore: class extends self.ITextInstance {},
	EffectMove: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Logo: class extends self.ISpriteInstance {},
	InfoBest: class extends self.ISpriteInstance {},
	InfoScore: class extends self.ISpriteInstance {},
	TextBest: class extends self.ITextInstance {},
	game_bg: class extends self.ISpriteInstance {},
	menu_bg: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {}
}