const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.EventGameplay_Event17_Act2,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.EventGameplay_Event35_Act8,
		C3.JavaScriptInEvents.EventMenu_Event2_Act1,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Touch: 0},
	{Collision: 0},
	{Fade: 0},
	{Solid: 0},
	{Sine: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Background: 0},
	{Rotate: 0},
	{EffectPlayer: 0},
	{Particles1: 0},
	{Enemy: 0},
	{Score: 0},
	{Particles2: 0},
	{EffectFade: 0},
	{Logo: 0},
	{ButtonStart: 0},
	{var_score: 0},
	{var_higher: 0},
	{Texts: 0},
	{SpriteFont: 0},
	{Splash: 0},
	{Particles3: 0},
	{Sprite: 0},
	{Bullet: 0},
	{Wrap: 0},
	{Sprite2: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text_percent: 0},
	{fade: 0},
	{Pin: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{var_difficulty: 0},
	{DeathType: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Collision: class extends self.ISpriteInstance {},
	Platform: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	EffectPlayer: class extends self.ISpriteInstance {},
	Particles1: class extends self.IParticlesInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	EffectFade: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.IArrayInstance {},
	Splash: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	fade: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {}
}