const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.JavaScriptInEvents.EventGameplay_Event10_Act2,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{Frame: 0},
	{Solid: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Lose: 0},
	{Bullet: 0},
	{Ball: 0},
	{Item: 0},
	{Touch: 0},
	{Keyboard: 0},
	{BallEffect: 0},
	{Particles: 0},
	{TextScore: 0},
	{ButtonL: 0},
	{ButtonR: 0},
	{Sine: 0},
	{Logo: 0},
	{Best: 0},
	{TextBest: 0},
	{EffectFade: 0},
	{New: 0},
	{LocalStorage: 0},
	{Credits: 0},
	{Browser: 0},
	{Audio: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{var_state: 0},
	{var_score: 0},
	{var_score_best: 0}
];

self.InstanceType = {
	Frame: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Lose: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Item: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	BallEffect: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	TextScore: class extends self.ITextInstance {},
	ButtonL: class extends self.ISpriteInstance {},
	ButtonR: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Best: class extends self.ISpriteInstance {},
	TextBest: class extends self.ITextInstance {},
	EffectFade: class extends self.ISpriteInstance {},
	New: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Credits: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {}
}