const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.XML,
		C3.Plugins.Json,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Behaviors.jumpthru,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Acts.StopAll,
		C3.JavaScriptInEvents.Event_level_general_Event34_Act1,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{bridge_02: 0},
	{bridge_01: 0},
	{castle_princess: 0},
	{ground_princess_01: 0},
	{bridge_03: 0},
	{city_princess: 0},
	{ground_02: 0},
	{ground_03: 0},
	{ground_01: 0},
	{ground_04: 0},
	{mountain_a_01: 0},
	{mountain_a_02: 0},
	{mountain_a_03: 0},
	{mountain_a_04: 0},
	{mountain_a_05: 0},
	{mountain_b_01: 0},
	{mountain_b_02: 0},
	{mountain_b_03: 0},
	{mountain_b_04: 0},
	{mountain_b_05: 0},
	{mountain_princess_01: 0},
	{mountain_princess_02: 0},
	{mountain_princess_03: 0},
	{mountain_princess_04: 0},
	{mountain_princess_05: 0},
	{Solid: 0},
	{water_01: 0},
	{sky_princess_01: 0},
	{sky_01: 0},
	{sky_princess_02: 0},
	{sky_02: 0},
	{bridge_bad: 0},
	{city_princess_final: 0},
	{check: 0},
	{checkpoint_01: 0},
	{checkpoint_02: 0},
	{checkpoint_03: 0},
	{checkpoint_04: 0},
	{checkpoint_05: 0},
	{Fade: 0},
	{attack_fire: 0},
	{effect_a: 0},
	{effect_b: 0},
	{effect_blow: 0},
	{effect_final: 0},
	{effect_restart: 0},
	{enemy_cat_death: 0},
	{level_diamant: 0},
	{level_final: 0},
	{level_gold: 0},
	{monster_death: 0},
	{princess_attack_01: 0},
	{princess_attack_02: 0},
	{enemy_bull_death: 0},
	{enemy_tutorial_explosion: 0},
	{level_effect: 0},
	{trinks_balloon_01: 0},
	{trinks_balloon_02: 0},
	{trinks_balloon_03: 0},
	{trinks_balloon_04: 0},
	{enemy_tutorial: 0},
	{trinks_balloon_05: 0},
	{trinks_balloon_06: 0},
	{trinks_balloon_07: 0},
	{Anchor: 0},
	{info_diamant: 0},
	{info_gold: 0},
	{info_life: 0},
	{info_life_count: 0},
	{info_bg: 0},
	{info_gold_font: 0},
	{bt_again: 0},
	{bt_home2: 0},
	{bt_sound: 0},
	{info_bg_02: 0},
	{info_bg_01: 0},
	{bt_play: 0},
	{bt_left: 0},
	{bt_right: 0},
	{DragDrop: 0},
	{bt_attack_jump: 0},
	{bt_pause: 0},
	{info_mouse: 0},
	{tutorial_keyboard: 0},
	{tutorial_touch_attack_jump: 0},
	{tutorial_touch_left: 0},
	{tutorial_touch_right: 0},
	{tutorial_touch_icon: 0},
	{enemy_blow_02: 0},
	{enemy_blow_01: 0},
	{life: 0},
	{life_count: 0},
	{motion: 0},
	{Platform: 0},
	{enemy_bull: 0},
	{enemy_blow_03: 0},
	{enemy_monster_body: 0},
	{enemy_cat: 0},
	{attack: 0},
	{distance: 0},
	{Bullet: 0},
	{enemy_monster_head: 0},
	{enemy_monster_point: 0},
	{enemy_boss: 0},
	{Princess: 0},
	{ScrollTo: 0},
	{princess_cam: 0},
	{princess_dust: 0},
	{trinks_childrens: 0},
	{brick_02: 0},
	{brick_03: 0},
	{brick_04: 0},
	{brick_05: 0},
	{brick_06: 0},
	{brick_long_01: 0},
	{brick_long_02: 0},
	{brick_long_03: 0},
	{brick_01: 0},
	{brick_mini_02: 0},
	{brick_mini_03: 0},
	{brick_mini_04: 0},
	{brick_mini_05: 0},
	{brick_mini_06: 0},
	{brick_mini_long_01: 0},
	{brick_mini_long_02: 0},
	{brick_mini_long_03: 0},
	{brush_01: 0},
	{brush_02: 0},
	{brush_03: 0},
	{brush_04: 0},
	{brush_05: 0},
	{brush_06: 0},
	{brick_mini_01: 0},
	{brush_princess_01: 0},
	{brush_princess_02: 0},
	{brush_princess_03: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Sine: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Touch: 0},
	{Video: 0},
	{XML: 0},
	{bt_level_01: 0},
	{level_edge: 0},
	{home_bg: 0},
	{home_sky: 0},
	{home_princess: 0},
	{bt_home: 0},
	{logo_home: 0},
	{logo_title: 0},
	{bt_level: 0},
	{level_bg_name: 0},
	{level_map: 0},
	{level_name: 0},
	{bt_level_02: 0},
	{bt_level_03: 0},
	{bt_level_04: 0},
	{level_princess: 0},
	{levels_princess_solid: 0},
	{princess_levels_dust: 0},
	{level: 0},
	{bg_achievement: 0},
	{levels_gold: 0},
	{levels_diamant: 0},
	{level_gold_font: 0},
	{bt_level_05: 0},
	{bt_level_06: 0},
	{bt_level_07: 0},
	{bt_level_08: 0},
	{level_map_bridge: 0},
	{level_cloud_01: 0},
	{level_cloud_02: 0},
	{level_cloud_03: 0},
	{logo_levels: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{JSON: 0},
	{Sprite3: 0},
	{Wrap: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{princess_attacks: 0},
	{enemies_blow: 0},
	{scenary_grounds: 0},
	{Jumpthru: 0},
	{scenary_mountains: 0},
	{scenary_bridges: 0},
	{scenary_bricks: 0},
	{checkpoints: 0},
	{scenary_bricks_fall: 0},
	{levels_clouds: 0},
	{level_tutorial: 0},
	{gameDiamant_01: 0},
	{gameGoldCount_01: 0},
	{PrincessAttack: 0},
	{PrincessAttackNow: 0},
	{PrincessDirection: 0},
	{PrincessJump: 0},
	{PrincessJumpTouch: 0},
	{PrincessLife: 0},
	{PrincessDeath: 0},
	{PrincessPow: 0},
	{PrincessPowPow: 0},
	{PrincessTouchCount: 0},
	{PrincessLifeCount: 0},
	{PrincessPowCount: 0},
	{gameCheckpoint: 0},
	{gameCheckNow: 0},
	{game: 0},
	{gameDiamant: 0},
	{gameGoldCount: 0},
	{gameSound: 0},
	{levelOk: 0},
	{levelsPrincessDirection: 0},
	{levelGo: 0},
	{levelNow: 0},
	{levelAgain: 0},
	{levelStatus_01: 0},
	{levelStatus_02: 0},
	{levelStatus_03: 0},
	{levelStatus_04: 0},
	{levelStatus_05: 0},
	{levelStatus_06: 0},
	{levelStatus_07: 0},
	{levelStatus_08: 0},
	{gameDiamant_02: 0},
	{gameGoldCount_02: 0},
	{detect_mouse: 0},
	{gameDiamant_03: 0},
	{gameGoldCount_03: 0},
	{gameDiamant_04: 0},
	{gameGoldCount_04: 0},
	{gameDiamant_05: 0},
	{gameGoldCount_05: 0},
	{gameDiamant_06: 0},
	{gameGoldCount_06: 0},
	{gameDiamant_07: 0},
	{gameGoldCount_07: 0},
	{gameDiamant_08: 0},
	{gameGoldCount_08: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	bridge_02: class extends self.ISpriteInstance {},
	bridge_01: class extends self.ISpriteInstance {},
	castle_princess: class extends self.ISpriteInstance {},
	ground_princess_01: class extends self.ISpriteInstance {},
	bridge_03: class extends self.ISpriteInstance {},
	city_princess: class extends self.ISpriteInstance {},
	ground_02: class extends self.ISpriteInstance {},
	ground_03: class extends self.ISpriteInstance {},
	ground_01: class extends self.ISpriteInstance {},
	ground_04: class extends self.ISpriteInstance {},
	mountain_a_01: class extends self.ISpriteInstance {},
	mountain_a_02: class extends self.ISpriteInstance {},
	mountain_a_03: class extends self.ISpriteInstance {},
	mountain_a_04: class extends self.ISpriteInstance {},
	mountain_a_05: class extends self.ISpriteInstance {},
	mountain_b_01: class extends self.ISpriteInstance {},
	mountain_b_02: class extends self.ISpriteInstance {},
	mountain_b_03: class extends self.ISpriteInstance {},
	mountain_b_04: class extends self.ISpriteInstance {},
	mountain_b_05: class extends self.ISpriteInstance {},
	mountain_princess_01: class extends self.ISpriteInstance {},
	mountain_princess_02: class extends self.ISpriteInstance {},
	mountain_princess_03: class extends self.ISpriteInstance {},
	mountain_princess_04: class extends self.ISpriteInstance {},
	mountain_princess_05: class extends self.ISpriteInstance {},
	water_01: class extends self.ISpriteInstance {},
	sky_princess_01: class extends self.ISpriteInstance {},
	sky_01: class extends self.ISpriteInstance {},
	sky_princess_02: class extends self.ISpriteInstance {},
	sky_02: class extends self.ISpriteInstance {},
	bridge_bad: class extends self.ISpriteInstance {},
	city_princess_final: class extends self.ISpriteInstance {},
	checkpoint_01: class extends self.ISpriteInstance {},
	checkpoint_02: class extends self.ISpriteInstance {},
	checkpoint_03: class extends self.ISpriteInstance {},
	checkpoint_04: class extends self.ISpriteInstance {},
	checkpoint_05: class extends self.ISpriteInstance {},
	attack_fire: class extends self.ISpriteInstance {},
	effect_a: class extends self.ISpriteInstance {},
	effect_b: class extends self.ISpriteInstance {},
	effect_blow: class extends self.ISpriteInstance {},
	effect_final: class extends self.ISpriteInstance {},
	effect_restart: class extends self.ISpriteInstance {},
	enemy_cat_death: class extends self.ISpriteInstance {},
	level_diamant: class extends self.ISpriteInstance {},
	level_final: class extends self.ISpriteInstance {},
	level_gold: class extends self.ISpriteInstance {},
	monster_death: class extends self.ISpriteInstance {},
	princess_attack_01: class extends self.ISpriteInstance {},
	princess_attack_02: class extends self.ISpriteInstance {},
	enemy_bull_death: class extends self.ISpriteInstance {},
	enemy_tutorial_explosion: class extends self.ISpriteInstance {},
	level_effect: class extends self.ISpriteInstance {},
	trinks_balloon_01: class extends self.ISpriteInstance {},
	trinks_balloon_02: class extends self.ISpriteInstance {},
	trinks_balloon_03: class extends self.ISpriteInstance {},
	trinks_balloon_04: class extends self.ISpriteInstance {},
	enemy_tutorial: class extends self.ISpriteInstance {},
	trinks_balloon_05: class extends self.ISpriteInstance {},
	trinks_balloon_06: class extends self.ISpriteInstance {},
	trinks_balloon_07: class extends self.ISpriteInstance {},
	info_diamant: class extends self.ISpriteInstance {},
	info_gold: class extends self.ISpriteInstance {},
	info_life: class extends self.ISpriteInstance {},
	info_life_count: class extends self.ISpriteInstance {},
	info_bg: class extends self.ISpriteInstance {},
	info_gold_font: class extends self.ISpriteFontInstance {},
	bt_again: class extends self.ISpriteInstance {},
	bt_home2: class extends self.ISpriteInstance {},
	bt_sound: class extends self.ISpriteInstance {},
	info_bg_02: class extends self.ISpriteInstance {},
	info_bg_01: class extends self.ISpriteInstance {},
	bt_play: class extends self.ISpriteInstance {},
	bt_left: class extends self.ISpriteInstance {},
	bt_right: class extends self.ISpriteInstance {},
	bt_attack_jump: class extends self.ISpriteInstance {},
	bt_pause: class extends self.ISpriteInstance {},
	info_mouse: class extends self.ISpriteInstance {},
	tutorial_keyboard: class extends self.ISpriteInstance {},
	tutorial_touch_attack_jump: class extends self.ISpriteInstance {},
	tutorial_touch_left: class extends self.ISpriteInstance {},
	tutorial_touch_right: class extends self.ISpriteInstance {},
	tutorial_touch_icon: class extends self.ISpriteInstance {},
	enemy_blow_02: class extends self.ISpriteInstance {},
	enemy_blow_01: class extends self.ISpriteInstance {},
	enemy_bull: class extends self.ISpriteInstance {},
	enemy_blow_03: class extends self.ISpriteInstance {},
	enemy_monster_body: class extends self.ISpriteInstance {},
	enemy_cat: class extends self.ISpriteInstance {},
	enemy_monster_head: class extends self.ISpriteInstance {},
	enemy_monster_point: class extends self.ISpriteInstance {},
	enemy_boss: class extends self.ISpriteInstance {},
	Princess: class extends self.ISpriteInstance {},
	princess_cam: class extends self.ISpriteInstance {},
	princess_dust: class extends self.ISpriteInstance {},
	trinks_childrens: class extends self.ISpriteInstance {},
	brick_02: class extends self.ISpriteInstance {},
	brick_03: class extends self.ISpriteInstance {},
	brick_04: class extends self.ISpriteInstance {},
	brick_05: class extends self.ISpriteInstance {},
	brick_06: class extends self.ISpriteInstance {},
	brick_long_01: class extends self.ISpriteInstance {},
	brick_long_02: class extends self.ISpriteInstance {},
	brick_long_03: class extends self.ISpriteInstance {},
	brick_01: class extends self.ISpriteInstance {},
	brick_mini_02: class extends self.ISpriteInstance {},
	brick_mini_03: class extends self.ISpriteInstance {},
	brick_mini_04: class extends self.ISpriteInstance {},
	brick_mini_05: class extends self.ISpriteInstance {},
	brick_mini_06: class extends self.ISpriteInstance {},
	brick_mini_long_01: class extends self.ISpriteInstance {},
	brick_mini_long_02: class extends self.ISpriteInstance {},
	brick_mini_long_03: class extends self.ISpriteInstance {},
	brush_01: class extends self.ISpriteInstance {},
	brush_02: class extends self.ISpriteInstance {},
	brush_03: class extends self.ISpriteInstance {},
	brush_04: class extends self.ISpriteInstance {},
	brush_05: class extends self.ISpriteInstance {},
	brush_06: class extends self.ISpriteInstance {},
	brick_mini_01: class extends self.ISpriteInstance {},
	brush_princess_01: class extends self.ISpriteInstance {},
	brush_princess_02: class extends self.ISpriteInstance {},
	brush_princess_03: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	XML: class extends self.IInstance {},
	bt_level_01: class extends self.ISpriteInstance {},
	level_edge: class extends self.ISpriteInstance {},
	home_bg: class extends self.ISpriteInstance {},
	home_sky: class extends self.ISpriteInstance {},
	home_princess: class extends self.ISpriteInstance {},
	bt_home: class extends self.ISpriteInstance {},
	logo_home: class extends self.ISpriteInstance {},
	logo_title: class extends self.ISpriteInstance {},
	bt_level: class extends self.ISpriteInstance {},
	level_bg_name: class extends self.ISpriteInstance {},
	level_map: class extends self.ISpriteInstance {},
	level_name: class extends self.ISpriteInstance {},
	bt_level_02: class extends self.ISpriteInstance {},
	bt_level_03: class extends self.ISpriteInstance {},
	bt_level_04: class extends self.ISpriteInstance {},
	level_princess: class extends self.ISpriteInstance {},
	levels_princess_solid: class extends self.ISpriteInstance {},
	princess_levels_dust: class extends self.ISpriteInstance {},
	bg_achievement: class extends self.ISpriteInstance {},
	levels_gold: class extends self.ISpriteInstance {},
	levels_diamant: class extends self.ISpriteInstance {},
	level_gold_font: class extends self.ISpriteFontInstance {},
	bt_level_05: class extends self.ISpriteInstance {},
	bt_level_06: class extends self.ISpriteInstance {},
	bt_level_07: class extends self.ISpriteInstance {},
	bt_level_08: class extends self.ISpriteInstance {},
	level_map_bridge: class extends self.ISpriteInstance {},
	level_cloud_01: class extends self.ISpriteInstance {},
	level_cloud_02: class extends self.ISpriteInstance {},
	level_cloud_03: class extends self.ISpriteInstance {},
	logo_levels: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	princess_attacks: class extends self.ISpriteInstance {},
	enemies_blow: class extends self.ISpriteInstance {},
	scenary_grounds: class extends self.ISpriteInstance {},
	scenary_mountains: class extends self.ISpriteInstance {},
	scenary_bridges: class extends self.ISpriteInstance {},
	scenary_bricks: class extends self.ISpriteInstance {},
	checkpoints: class extends self.ISpriteInstance {},
	scenary_bricks_fall: class extends self.ISpriteInstance {},
	levels_clouds: class extends self.ISpriteInstance {}
}