const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.XML,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.video,
		C3.Plugins.Json,
		C3.Behaviors.Pin,
		C3.Behaviors.jumpthru,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Events_general_Event61_Act1,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.AJAX.Acts.Request
	];
};
self.C3_JsPropNameTable = [
	{name: 0},
	{chain: 0},
	{Platform: 0},
	{position_all: 0},
	{position_sled1: 0},
	{position_sled3: 0},
	{position_sled2: 0},
	{position_sled5: 0},
	{position_sleigh: 0},
	{position_sled4: 0},
	{santa_claus: 0},
	{sled: 0},
	{Solid: 0},
	{sleigh: 0},
	{ScrollTo: 0},
	{sleigh_cam: 0},
	{sleigh_cam_ground: 0},
	{sleigh_brick: 0},
	{Sine: 0},
	{witchTheme: 0},
	{sleigh2_theme: 0},
	{bg_ground_01: 0},
	{bg_ground_02: 0},
	{bg_sky_01: 0},
	{bg_trees_01: 0},
	{bg_limit_top: 0},
	{final_prettie_01: 0},
	{final_prettie_02: 0},
	{final_tree: 0},
	{ground_slope_01: 0},
	{bg_trees_slope_01: 0},
	{bg_ground_snow: 0},
	{bg_mountains: 0},
	{bg_mountains_slope: 0},
	{Fade: 0},
	{bg_shooting_star: 0},
	{shooting_star_create: 0},
	{Sine2: 0},
	{balloon_red: 0},
	{balloon_red_bum: 0},
	{balloon_yellow: 0},
	{balloon_yellow_bum: 0},
	{balloon_red2: 0},
	{balloon_yellow2: 0},
	{bubble_bum: 0},
	{bubble_gift_01: 0},
	{bubble_gift_03: 0},
	{bubble_gift_05: 0},
	{bubble_gift_06: 0},
	{bubble_gift_07: 0},
	{bubble_gift_04: 0},
	{bubble_gift_08: 0},
	{bubble_gift_09: 0},
	{bubble_gift_02: 0},
	{bubble_gift_10: 0},
	{gift_01: 0},
	{gift_03: 0},
	{gift_05: 0},
	{gift_06: 0},
	{gift_07: 0},
	{gift_08: 0},
	{gift_04: 0},
	{gift_09: 0},
	{gift_10: 0},
	{gift_02: 0},
	{gift_catch: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{XML: 0},
	{bt_level_01: 0},
	{bt_level_02: 0},
	{effect_down: 0},
	{effect_logo: 0},
	{effect_up: 0},
	{home_balloons: 0},
	{home_bt_play: 0},
	{home_bg_red: 0},
	{home_sleds: 0},
	{levels_balloons: 0},
	{levels_bg_red: 0},
	{logo_christmas_furious: 0},
	{bt_level_03: 0},
	{bt_level_04: 0},
	{bt_level_05: 0},
	{bt_level_06: 0},
	{tutorial_bt_ok: 0},
	{tutorial_commands: 0},
	{bg_layout: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{level: 0},
	{levels_font: 0},
	{bg_red: 0},
	{Anchor: 0},
	{bg_pause: 0},
	{bt_again: 0},
	{bt_home: 0},
	{bt_pause: 0},
	{bt_play: 0},
	{bt_sound: 0},
	{final_gift: 0},
	{life: 0},
	{final_font: 0},
	{tutorial: 0},
	{Video: 0},
	{JSON: 0},
	{Pin: 0},
	{broom_effect: 0},
	{bg_dummy: 0},
	{halloween_tree: 0},
	{moon: 0},
	{ad_board: 0},
	{only_house: 0},
	{grass: 0},
	{ground_tileset: 0},
	{final_tree2: 0},
	{bg_mid_2_with_brand_logo: 0},
	{grounds: 0},
	{sleigh_all: 0},
	{bubbles: 0},
	{Jumpthru: 0},
	{gifts: 0},
	{buttons: 0},
	{gifts_level: 0},
	{game_sound: 0},
	{game_now: 0},
	{game: 0},
	{game_commands: 0},
	{sleigh_fall: 0},
	{sleigh_life: 0},
	{sleigh_motion: 0},
	{detect_mouse: 0},
	{levels_01_active: 0},
	{levels_02_active: 0},
	{levels_03_active: 0},
	{levels_04_active: 0},
	{levels_05_active: 0},
	{levels_06_active: 0},
	{effect_layout: 0},
	{effect_go: 0},
	{gifts_level_01: 0},
	{gifts_level_02: 0},
	{gifts_level_03: 0},
	{gifts_level_04: 0},
	{gifts_level_05: 0},
	{gifts_level_06: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	chain: class extends self.ISpriteInstance {},
	position_all: class extends self.ISpriteInstance {},
	position_sled1: class extends self.ISpriteInstance {},
	position_sled3: class extends self.ISpriteInstance {},
	position_sled2: class extends self.ISpriteInstance {},
	position_sled5: class extends self.ISpriteInstance {},
	position_sleigh: class extends self.ISpriteInstance {},
	position_sled4: class extends self.ISpriteInstance {},
	santa_claus: class extends self.ISpriteInstance {},
	sled: class extends self.ISpriteInstance {},
	sleigh: class extends self.ISpriteInstance {},
	sleigh_cam: class extends self.ISpriteInstance {},
	sleigh_cam_ground: class extends self.ISpriteInstance {},
	sleigh_brick: class extends self.ISpriteInstance {},
	witchTheme: class extends self.ISpriteInstance {},
	sleigh2_theme: class extends self.ISpriteInstance {},
	bg_ground_01: class extends self.ISpriteInstance {},
	bg_ground_02: class extends self.ISpriteInstance {},
	bg_sky_01: class extends self.ITiledBackgroundInstance {},
	bg_trees_01: class extends self.ITiledBackgroundInstance {},
	bg_limit_top: class extends self.ISpriteInstance {},
	final_prettie_01: class extends self.ITiledBackgroundInstance {},
	final_prettie_02: class extends self.ITiledBackgroundInstance {},
	final_tree: class extends self.ITiledBackgroundInstance {},
	ground_slope_01: class extends self.ISpriteInstance {},
	bg_trees_slope_01: class extends self.ITiledBackgroundInstance {},
	bg_ground_snow: class extends self.ISpriteInstance {},
	bg_mountains: class extends self.ISpriteInstance {},
	bg_mountains_slope: class extends self.ISpriteInstance {},
	bg_shooting_star: class extends self.ISpriteInstance {},
	shooting_star_create: class extends self.ISpriteInstance {},
	balloon_red: class extends self.ISpriteInstance {},
	balloon_red_bum: class extends self.ISpriteInstance {},
	balloon_yellow: class extends self.ISpriteInstance {},
	balloon_yellow_bum: class extends self.ISpriteInstance {},
	balloon_red2: class extends self.ISpriteInstance {},
	balloon_yellow2: class extends self.ISpriteInstance {},
	bubble_bum: class extends self.ISpriteInstance {},
	bubble_gift_01: class extends self.ISpriteInstance {},
	bubble_gift_03: class extends self.ISpriteInstance {},
	bubble_gift_05: class extends self.ISpriteInstance {},
	bubble_gift_06: class extends self.ISpriteInstance {},
	bubble_gift_07: class extends self.ISpriteInstance {},
	bubble_gift_04: class extends self.ISpriteInstance {},
	bubble_gift_08: class extends self.ISpriteInstance {},
	bubble_gift_09: class extends self.ISpriteInstance {},
	bubble_gift_02: class extends self.ISpriteInstance {},
	bubble_gift_10: class extends self.ISpriteInstance {},
	gift_01: class extends self.ISpriteInstance {},
	gift_03: class extends self.ISpriteInstance {},
	gift_05: class extends self.ISpriteInstance {},
	gift_06: class extends self.ISpriteInstance {},
	gift_07: class extends self.ISpriteInstance {},
	gift_08: class extends self.ISpriteInstance {},
	gift_04: class extends self.ISpriteInstance {},
	gift_09: class extends self.ISpriteInstance {},
	gift_10: class extends self.ISpriteInstance {},
	gift_02: class extends self.ISpriteInstance {},
	gift_catch: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	bt_level_01: class extends self.ISpriteInstance {},
	bt_level_02: class extends self.ISpriteInstance {},
	effect_down: class extends self.ISpriteInstance {},
	effect_logo: class extends self.ISpriteInstance {},
	effect_up: class extends self.ISpriteInstance {},
	home_balloons: class extends self.ISpriteInstance {},
	home_bt_play: class extends self.ISpriteInstance {},
	home_bg_red: class extends self.ISpriteInstance {},
	home_sleds: class extends self.ISpriteInstance {},
	levels_balloons: class extends self.ISpriteInstance {},
	levels_bg_red: class extends self.ISpriteInstance {},
	logo_christmas_furious: class extends self.ISpriteInstance {},
	bt_level_03: class extends self.ISpriteInstance {},
	bt_level_04: class extends self.ISpriteInstance {},
	bt_level_05: class extends self.ISpriteInstance {},
	bt_level_06: class extends self.ISpriteInstance {},
	tutorial_bt_ok: class extends self.ISpriteInstance {},
	tutorial_commands: class extends self.ISpriteInstance {},
	bg_layout: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	levels_font: class extends self.ISpriteFontInstance {},
	bg_red: class extends self.ISpriteInstance {},
	bg_pause: class extends self.ISpriteInstance {},
	bt_again: class extends self.ISpriteInstance {},
	bt_home: class extends self.ISpriteInstance {},
	bt_pause: class extends self.ISpriteInstance {},
	bt_play: class extends self.ISpriteInstance {},
	bt_sound: class extends self.ISpriteInstance {},
	final_gift: class extends self.ISpriteInstance {},
	life: class extends self.ISpriteInstance {},
	final_font: class extends self.ISpriteFontInstance {},
	tutorial: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	JSON: class extends self.IJSONInstance {},
	broom_effect: class extends self.ISpriteInstance {},
	bg_dummy: class extends self.ISpriteInstance {},
	halloween_tree: class extends self.ISpriteInstance {},
	moon: class extends self.ISpriteInstance {},
	ad_board: class extends self.ISpriteInstance {},
	only_house: class extends self.ISpriteInstance {},
	grass: class extends self.ISpriteInstance {},
	ground_tileset: class extends self.ITiledBackgroundInstance {},
	final_tree2: class extends self.ISpriteInstance {},
	bg_mid_2_with_brand_logo: class extends self.ISpriteInstance {},
	grounds: class extends self.ISpriteInstance {},
	sleigh_all: class extends self.ISpriteInstance {},
	bubbles: class extends self.ISpriteInstance {},
	gifts: class extends self.ISpriteInstance {},
	buttons: class extends self.ISpriteInstance {}
}