const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Sin,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.advert,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.scrolly,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.JavaScriptInEvents.GameEvents_Event126_Act2,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{create: 0},
	{dotLabel: 0},
	{string: 0},
	{register: 0},
	{Tween: 0},
	{BlackC: 0},
	{w: 0},
	{h: 0},
	{BtnBack: 0},
	{BtnClose: 0},
	{BtnInfo: 0},
	{BtnPlay: 0},
	{BtnSound: 0},
	{BtnMusic: 0},
	{Pin: 0},
	{Info: 0},
	{InfoBox: 0},
	{n: 0},
	{BtnLevel: 0},
	{LEVELDONEhome: 0},
	{LEVELDONEnext: 0},
	{LEVELDONEretry: 0},
	{PAUSEhome: 0},
	{PAUSEmusic: 0},
	{PAUSEreset: 0},
	{PAUSEsound: 0},
	{LEVELDONEback: 0},
	{BtnDoonDookStudio: 0},
	{UIpause: 0},
	{Title: 0},
	{PAUSEback: 0},
	{txtBtnLevel: 0},
	{PAUSEclose: 0},
	{nextLevel: 0},
	{prevLevel: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{levelsData: 0},
	{txtLevel: 0},
	{background: 0},
	{hostsCenterHolder: 0},
	{place: 0},
	{LEVELFAILEDback: 0},
	{MAINbackground: 0},
	{hand: 0},
	{levelBack: 0},
	{levelLabel: 0},
	{posX: 0},
	{posY: 0},
	{hasPreInfectionLine: 0},
	{preInfectionCenter: 0},
	{infectionCenter: 0},
	{infected: 0},
	{preInfected: 0},
	{hasInfectionLine: 0},
	{host: 0},
	{DragDrop: 0},
	{MoveTo: 0},
	{virus: 0},
	{hostPreInfectionLine: 0},
	{virusPlatform: 0},
	{firstX: 0},
	{lastX: 0},
	{virusesCenterHolder: 0},
	{hostInfectionLine: 0},
	{active: 0},
	{Sine: 0},
	{hostAura: 0},
	{virusTarget: 0},
	{touchHolder: 0},
	{Text: 0},
	{AJAX: 0},
	{JSON: 0},
	{MobileAdvert: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{Video: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{fade: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{FButtons: 0},
	{hostsFamily: 0},
	{virusesFamily: 0},
	{hostSpreadLinesFamily: 0},
	{hostSpreadLinesFamily2: 0},
	{Pin2: 0},
	{pauseFamily: 0},
	{levelDoneFamily: 0},
	{infectedsFamily: 0},
	{touchedVirus: 0},
	{virusTargeted: 0},
	{lastPlantedVirus: 0},
	{levelsDataSet: 0},
	{levelData: 0},
	{hostsData: 0},
	{virusesData: 0},
	{touchStartX: 0},
	{touchStartY: 0},
	{timeToPlay: 0},
	{rowCount: 0},
	{leftHost: 0},
	{rightHost: 0},
	{topHost: 0},
	{bottomHost: 0},
	{level: 0},
	{Sound: 0},
	{Music: 0},
	{CamOn: 0},
	{Dragging: 0},
	{DragScrollY: 0},
	{DragTouchY: 0},
	{DragTouchSpd: 0},
	{DragTouchDir: 0},
	{MaxTop: 0},
	{MinBottom: 0},
	{PassedLevels: 0},
	{LevelSelectTimer: 0},
	{LCstring: 0},
	{LCHostString: 0},
	{LCvirusString: 0}
];

self.InstanceType = {
	create: class extends self.IButtonInstance {},
	dotLabel: class extends self.ITextInstance {},
	string: class extends self.ITextInputInstance {},
	register: class extends self.IButtonInstance {},
	BlackC: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	Info: class extends self.ISpriteInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	LEVELDONEhome: class extends self.ISpriteInstance {},
	LEVELDONEnext: class extends self.ISpriteInstance {},
	LEVELDONEretry: class extends self.ISpriteInstance {},
	PAUSEhome: class extends self.ISpriteInstance {},
	PAUSEmusic: class extends self.ISpriteInstance {},
	PAUSEreset: class extends self.ISpriteInstance {},
	PAUSEsound: class extends self.ISpriteInstance {},
	LEVELDONEback: class extends self.ISpriteInstance {},
	BtnDoonDookStudio: class extends self.ISpriteInstance {},
	UIpause: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	PAUSEback: class extends self.ISpriteInstance {},
	txtBtnLevel: class extends self.ISpriteFontInstance {},
	PAUSEclose: class extends self.ISpriteInstance {},
	nextLevel: class extends self.ISpriteInstance {},
	prevLevel: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	levelsData: class extends self.IDictionaryInstance {},
	txtLevel: class extends self.ISpriteFontInstance {},
	background: class extends self.ISpriteInstance {},
	hostsCenterHolder: class extends self.ISpriteInstance {},
	place: class extends self.ISpriteInstance {},
	LEVELFAILEDback: class extends self.ISpriteInstance {},
	MAINbackground: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	levelBack: class extends self.ISpriteInstance {},
	levelLabel: class extends self.ISpriteInstance {},
	host: class extends self.ISpriteInstance {},
	virus: class extends self.ISpriteInstance {},
	hostPreInfectionLine: class extends self.ISpriteInstance {},
	virusPlatform: class extends self.ISpriteInstance {},
	virusesCenterHolder: class extends self.ISpriteInstance {},
	hostInfectionLine: class extends self.ISpriteInstance {},
	hostAura: class extends self.ISpriteInstance {},
	virusTarget: class extends self.ISpriteInstance {},
	touchHolder: class extends self.ISpriteInstance {},
	infected: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	MobileAdvert: class extends self.IInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	hostsFamily: class extends self.ISpriteInstance {},
	virusesFamily: class extends self.ISpriteInstance {},
	hostSpreadLinesFamily: class extends self.ISpriteInstance {},
	hostSpreadLinesFamily2: class extends self.ISpriteInstance {},
	pauseFamily: class extends self.ISpriteInstance {},
	levelDoneFamily: class extends self.ISpriteInstance {},
	infectedsFamily: class extends self.ISpriteInstance {}
}