const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.video,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.GameEventSheet_Event87_Act1,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.GameEventSheet_Event92_Act2,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.GameEventSheet_Event105_Act7,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.JavaScriptInEvents.MenuEventSheet_Event3_Act6,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Browser.Cnds.IsOnline,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Platform_game: 0},
	{fon: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{Block: 0},
	{ScrollTo: 0},
	{sheep: 0},
	{Leftg: 0},
	{Rightg: 0},
	{up: 0},
	{pausa: 0},
	{Touch: 0},
	{id: 0},
	{mir: 0},
	{anim: 0},
	{power: 0},
	{Platform: 0},
	{Wrap: 0},
	{gg: 0},
	{Spawn: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sprite12: 0},
	{Fade: 0},
	{Sprite13: 0},
	{enem: 0},
	{timer: 0},
	{enemu: 0},
	{score: 0},
	{Array: 0},
	{Sprite7: 0},
	{play: 0},
	{Hoe_button: 0},
	{Sprite10: 0},
	{music: 0},
	{sound: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{go: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{twitter: 0},
	{facebook: 0},
	{Sprite19: 0},
	{Audio: 0},
	{GameResultsFont: 0},
	{Browser: 0},
	{StartGame: 0},
	{LastScoreFont: 0},
	{Keyboard: 0},
	{Next_level: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite11: 0},
	{LocalStorage: 0},
	{Video: 0},
	{Sprite15: 0},
	{AJAX: 0},
	{JSON: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{Particles: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Particles2: 0},
	{Sprite16: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Pin: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{Level: 0},
	{NextScore: 0},
	{Best: 0},
	{Musick: 0},
	{Saund: 0},
	{GG: 0},
	{Score: 0},
	{Score2: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0},
	{GAME_NAME: 0},
	{DESCRIPTION: 0},
	{IMAGE: 0},
	{REDIRECT_URL: 0}
];

self.InstanceType = {
	Platform_game: class extends self.ISpriteInstance {},
	fon: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	sheep: class extends self.ISpriteInstance {},
	Leftg: class extends self.ISpriteInstance {},
	Rightg: class extends self.ISpriteInstance {},
	up: class extends self.ISpriteInstance {},
	pausa: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	gg: class extends self.ISpriteInstance {},
	Spawn: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	enem: class extends self.ISpriteInstance {},
	enemu: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	Hoe_button: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	music: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	go: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	twitter: class extends self.ISpriteInstance {},
	facebook: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	GameResultsFont: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	StartGame: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	Keyboard: class extends self.IInstance {},
	Next_level: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Fade: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {}
}