const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Plugins.Browser,
		C3.Plugins.Button,
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.video,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.JavaScriptInEvents.Gamesheet_Event179_Act4,
		C3.Plugins.System.Exps.find,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{Array: 0},
	{Audio: 0},
	{Tween: 0},
	{BlackC: 0},
	{LRight: 0},
	{LLeft: 0},
	{LTop: 0},
	{LBottom: 0},
	{LinesCreated: 0},
	{Rotatable: 0},
	{AngTarget: 0},
	{Dragging: 0},
	{HostX: 0},
	{HostY: 0},
	{MySpot: 0},
	{ConnectedList: 0},
	{Block: 0},
	{Browser: 0},
	{BtnBack: 0},
	{BtnClose: 0},
	{BtnHome: 0},
	{BtnInfo: 0},
	{n: 0},
	{BtnLevel: 0},
	{BtnMusic: 0},
	{BtnNext: 0},
	{BtnPause: 0},
	{BtnPlay: 0},
	{BtnReset: 0},
	{BtnSound: 0},
	{Button: 0},
	{Cam: 0},
	{Function: 0},
	{InfoBox: 0},
	{Keyboard: 0},
	{parent: 0},
	{ConnectedTo: 0},
	{Line: 0},
	{LocalStorage: 0},
	{LvCompleteBox: 0},
	{MobileAdvert: 0},
	{Mouse: 0},
	{PauseBox: 0},
	{PlatformInfo: 0},
	{HasBlock: 0},
	{xx: 0},
	{yy: 0},
	{Spot: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{TextBox: 0},
	{Sine: 0},
	{Title: 0},
	{Touch: 0},
	{txtBtnLevel: 0},
	{txtLevel: 0},
	{Video: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{Pin: 0},
	{FLine: 0},
	{FBlock: 0},
	{FSpot: 0},
	{FButtons: 0},
	{FPopups: 0},
	{TouchStartX: 0},
	{TouchStartY: 0},
	{TouchedBlock: 0},
	{SelectedSpot: 0},
	{Size: 0},
	{CodeText: 0},
	{CodeGet: 0},
	{Level: 0},
	{Pause: 0},
	{LevelComplete: 0},
	{LevelStartTimer: 0},
	{Left_: 0},
	{Right_: 0},
	{Top_: 0},
	{Bottom_: 0},
	{dist: 0},
	{angl: 0},
	{vLevel: 0},
	{vSound: 0},
	{vMusic: 0},
	{vPassedLevels: 0},
	{Size2: 0},
	{Hor: 0},
	{Ver: 0},
	{Code: 0},
	{Dir: 0},
	{Num: 0},
	{BlockUID: 0},
	{Info: 0},
	{Sound: 0},
	{Music: 0},
	{CamOn: 0},
	{DragScrollY: 0},
	{DragTouchY: 0},
	{DragTouchSpd: 0},
	{DragTouchDir: 0},
	{MaxTop: 0},
	{MinBottom: 0},
	{PassedLevels: 0},
	{Swipe: 0},
	{LevelSelectTimer: 0},
	{AllLevels: 0},
	{AllLevelsN: 0},
	{Interstitial_ID: 0},
	{InterstitialVideo_ID: 0},
	{ShowVideoAd: 0},
	{vLastX: 0},
	{vLastY: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	BlackC: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Cam: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Line: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	LvCompleteBox: class extends self.ISpriteInstance {},
	MobileAdvert: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PauseBox: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Spot: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TextBox: class extends self.ITextInputInstance {},
	Title: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	txtBtnLevel: class extends self.ISpriteFontInstance {},
	txtLevel: class extends self.ISpriteFontInstance {},
	Video: class extends self.IWorldInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	FLine: class extends self.ISpriteInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FSpot: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FPopups: class extends self.ISpriteInstance {}
}