const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.advert,
		C3.Plugins.Particles,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Text.Exps.PickedCount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Text.Exps.Count,
		C3.JavaScriptInEvents.Esgame_Event26_Act1,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.Esgame_Event38_Act1,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{btn_back: 0},
	{btn_level1: 0},
	{btn_easy: 0},
	{btn_level2: 0},
	{btn_hard: 0},
	{btnMenu: 0},
	{btnAudio: 0},
	{Sine: 0},
	{btnPlay: 0},
	{btn_medium: 0},
	{btnHome: 0},
	{btnCredits: 0},
	{btnTwitter: 0},
	{btn_level3: 0},
	{btnFacebook: 0},
	{Keyboard: 0},
	{Browser: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{txt_record_level1: 0},
	{txt_score: 0},
	{txt_record_level3: 0},
	{txt_time_middle: 0},
	{txt_time_min: 0},
	{txt_record_level2: 0},
	{txt_time_seg: 0},
	{bgs_menus: 0},
	{bg_levels: 0},
	{credits_screen: 0},
	{initialScreen: 0},
	{arrow_choose: 0},
	{infinity_symbol: 0},
	{interrogations: 0},
	{word: 0},
	{letter: 0},
	{line1: 0},
	{line2: 0},
	{red_arrow: 0},
	{txt_multiply_debug: 0},
	{mouse_marker: 0},
	{time_over: 0},
	{you_win: 0},
	{AJAX: 0},
	{JSON: 0},
	{MobileAdvert: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{LevelParticles: 0},
	{Video: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{multiplyHardScore: 0},
	{gameover: 0},
	{minute: 0},
	{second: 0},
	{score: 0},
	{difficulty: 0},
	{Lenght: 0},
	{Select: 0},
	{ListWord: 0},
	{chooose: 0},
	{record1: 0},
	{record2: 0},
	{record3: 0},
	{LSrecord1: 0},
	{LSrecord2: 0},
	{LSrecord3: 0},
	{audio: 0}
];

self.InstanceType = {
	btn_back: class extends self.ISpriteInstance {},
	btn_level1: class extends self.ISpriteInstance {},
	btn_easy: class extends self.ISpriteInstance {},
	btn_level2: class extends self.ISpriteInstance {},
	btn_hard: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnAudio: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btn_medium: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnTwitter: class extends self.ISpriteInstance {},
	btn_level3: class extends self.ISpriteInstance {},
	btnFacebook: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	txt_record_level1: class extends self.ISpriteFontInstance {},
	txt_score: class extends self.ISpriteFontInstance {},
	txt_record_level3: class extends self.ISpriteFontInstance {},
	txt_time_middle: class extends self.ISpriteFontInstance {},
	txt_time_min: class extends self.ISpriteFontInstance {},
	txt_record_level2: class extends self.ISpriteFontInstance {},
	txt_time_seg: class extends self.ISpriteFontInstance {},
	bgs_menus: class extends self.ISpriteInstance {},
	bg_levels: class extends self.ISpriteInstance {},
	credits_screen: class extends self.ISpriteInstance {},
	initialScreen: class extends self.ISpriteInstance {},
	arrow_choose: class extends self.ISpriteInstance {},
	infinity_symbol: class extends self.ISpriteInstance {},
	interrogations: class extends self.ISpriteInstance {},
	word: class extends self.ITextInstance {},
	letter: class extends self.ITextInstance {},
	line1: class extends self.ISpriteInstance {},
	line2: class extends self.ISpriteInstance {},
	red_arrow: class extends self.ISpriteInstance {},
	txt_multiply_debug: class extends self.ITextInstance {},
	mouse_marker: class extends self.ISpriteInstance {},
	time_over: class extends self.ISpriteInstance {},
	you_win: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	MobileAdvert: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	LevelParticles: class extends self.IParticlesInstance {},
	Video: class extends self.IWorldInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {}
}