const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Keyboard,
		C3.Plugins.Timeline,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.LOS,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Tween,
		C3.Plugins.video,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Browser.Cnds.IsOnline,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.IsAnyPaused,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.JavaScriptInEvents.Winscreen_Event15_Act1,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{AJAX: 0},
	{Asdsadset42x: 0},
	{Audio: 0},
	{Browser: 0},
	{JSON: 0},
	{Keyboard: 0},
	{TimelineController: 0},
	{Touch: 0},
	{Sine: 0},
	{BackBtn: 0},
	{Button: 0},
	{Pin: 0},
	{OkBtnLose: 0},
	{OkBtnWin: 0},
	{StartButton: 0},
	{HomeBtn: 0},
	{LeftBtn: 0},
	{MuteButton: 0},
	{RightBtn: 0},
	{RightBtn2: 0},
	{RightBtn3: 0},
	{RightBtn4: 0},
	{Mode1Btn: 0},
	{Mode2Btn: 0},
	{ModeSelect: 0},
	{SkinBTN1: 0},
	{SkinBTN10: 0},
	{SkinBTN2: 0},
	{SkinBTN3: 0},
	{SkinBTN4: 0},
	{SkinBTN5: 0},
	{SkinBTN6: 0},
	{SkinBTN7: 0},
	{SkinBTN8: 0},
	{SkinBTN9: 0},
	{SlectorP1: 0},
	{SlectorP2: 0},
	{SelectorSinglePlayer: 0},
	{Winscreen: 0},
	{WinscreenVS: 0},
	{LoseScreen: 0},
	{Jump: 0},
	{Movement: 0},
	{Platform: 0},
	{LineOfSight: 0},
	{CPUPlayer: 0},
	{Player1: 0},
	{Player2: 0},
	{random_player: 0},
	{Hitable: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{Ball: 0},
	{BallShadow: 0},
	{Fade: 0},
	{BallTrail: 0},
	{BlueFog: 0},
	{cam: 0},
	{CharacterBackground: 0},
	{GoalLogo: 0},
	{KickOff: 0},
	{GameOverBackground: 0},
	{GoalFont: 0},
	{GoalP1: 0},
	{GoalP2: 0},
	{FieldBackground: 0},
	{JumpEffect: 0},
	{LightsEffect: 0},
	{ScoreBoard: 0},
	{ShopTittle: 0},
	{Sprite7: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{VersusBKBlue: 0},
	{VersusBKRed: 0},
	{VersusScreen: 0},
	{WinScreenBackground: 0},
	{Player1BackFoot: 0},
	{Player1FootCollition: 0},
	{Player1HeadBack: 0},
	{Player1HeadFont: 0},
	{Player2BackFoot: 0},
	{Player2FootCollition: 0},
	{Player2HeadBack: 0},
	{Player2HeadFront: 0},
	{PlayerHeadP3: 0},
	{PlayerHeadP4: 0},
	{PlayerHeadP5: 0},
	{PlayerHeadP6: 0},
	{RealPLayer1: 0},
	{RealPLayer2: 0},
	{Solid: 0},
	{GoalLimit: 0},
	{GoalscoreP1: 0},
	{GoalscoreP2: 0},
	{FieldLimit: 0},
	{FloorSolid: 0},
	{ColorParticlesBlue: 0},
	{ColorParticlesGreen: 0},
	{ColorParticlesLight: 0},
	{ColorParticlesPink: 0},
	{ColorParticlesRed: 0},
	{ColorParticlesYellow: 0},
	{P1LoseScoreFont: 0},
	{P1Scorefont: 0},
	{P1WinScoreFont: 0},
	{P2LoseScoreFont: 0},
	{P2Scorefont: 0},
	{P2WinScoreFont: 0},
	{MatchTimeFont: 0},
	{Tween: 0},
	{GameTittle: 0},
	{GameTittle2: 0},
	{Fireflies: 0},
	{light: 0},
	{deco: 0},
	{menu_ball: 0},
	{FadeScreen: 0},
	{RotateScreen: 0},
	{SmokeParticles: 0},
	{SmokeParticles2: 0},
	{MoreGameButton: 0},
	{RestartButton: 0},
	{PlayerShadow: 0},
	{Player2Shadow: 0},
	{PlayersBoard: 0},
	{MenuBackground: 0},
	{DifficultUI: 0},
	{WinScreenFloor: 0},
	{Video: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite6: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Anchor: 0},
	{Family1: 0},
	{BackgroundIMG: 0},
	{OpponentSkin: 0},
	{IAlevel: 0},
	{Lastgoal: 0},
	{Matchtime: 0},
	{Playing: 0},
	{P2SCORE: 0},
	{P1SCORE: 0},
	{Highfoot: 0},
	{HighfootP2: 0},
	{Lowfoot: 0},
	{LowfootP2: 0},
	{Sound: 0},
	{IsScreenRotate: 0},
	{SkinSelect: 0},
	{Match: 0}
];

self.InstanceType = {
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Asdsadset42x: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Keyboard: class extends self.IInstance {},
	TimelineController: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BackBtn: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	OkBtnLose: class extends self.ISpriteInstance {},
	OkBtnWin: class extends self.ISpriteInstance {},
	StartButton: class extends self.ISpriteInstance {},
	HomeBtn: class extends self.ISpriteInstance {},
	LeftBtn: class extends self.ISpriteInstance {},
	MuteButton: class extends self.ISpriteInstance {},
	RightBtn: class extends self.ISpriteInstance {},
	RightBtn2: class extends self.ISpriteInstance {},
	RightBtn3: class extends self.ISpriteInstance {},
	RightBtn4: class extends self.ISpriteInstance {},
	Mode1Btn: class extends self.ISpriteInstance {},
	Mode2Btn: class extends self.ISpriteInstance {},
	ModeSelect: class extends self.ISpriteInstance {},
	SkinBTN1: class extends self.ISpriteInstance {},
	SkinBTN10: class extends self.ISpriteInstance {},
	SkinBTN2: class extends self.ISpriteInstance {},
	SkinBTN3: class extends self.ISpriteInstance {},
	SkinBTN4: class extends self.ISpriteInstance {},
	SkinBTN5: class extends self.ISpriteInstance {},
	SkinBTN6: class extends self.ISpriteInstance {},
	SkinBTN7: class extends self.ISpriteInstance {},
	SkinBTN8: class extends self.ISpriteInstance {},
	SkinBTN9: class extends self.ISpriteInstance {},
	SlectorP1: class extends self.ISpriteInstance {},
	SlectorP2: class extends self.ISpriteInstance {},
	SelectorSinglePlayer: class extends self.ISpriteInstance {},
	Winscreen: class extends self.ISpriteInstance {},
	WinscreenVS: class extends self.ISpriteInstance {},
	LoseScreen: class extends self.ISpriteInstance {},
	CPUPlayer: class extends self.ISpriteInstance {},
	Player1: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	random_player: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BallShadow: class extends self.ISpriteInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	BlueFog: class extends self.ISpriteInstance {},
	cam: class extends self.ISpriteInstance {},
	CharacterBackground: class extends self.ISpriteInstance {},
	GoalLogo: class extends self.ISpriteInstance {},
	KickOff: class extends self.ISpriteInstance {},
	GameOverBackground: class extends self.ISpriteInstance {},
	GoalFont: class extends self.ISpriteInstance {},
	GoalP1: class extends self.ISpriteInstance {},
	GoalP2: class extends self.ISpriteInstance {},
	FieldBackground: class extends self.ISpriteInstance {},
	JumpEffect: class extends self.ISpriteInstance {},
	LightsEffect: class extends self.ISpriteInstance {},
	ScoreBoard: class extends self.ISpriteInstance {},
	ShopTittle: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	VersusBKBlue: class extends self.ITiledBackgroundInstance {},
	VersusBKRed: class extends self.ITiledBackgroundInstance {},
	VersusScreen: class extends self.ISpriteInstance {},
	WinScreenBackground: class extends self.ISpriteInstance {},
	Player1BackFoot: class extends self.ISpriteInstance {},
	Player1FootCollition: class extends self.ISpriteInstance {},
	Player1HeadBack: class extends self.ISpriteInstance {},
	Player1HeadFont: class extends self.ISpriteInstance {},
	Player2BackFoot: class extends self.ISpriteInstance {},
	Player2FootCollition: class extends self.ISpriteInstance {},
	Player2HeadBack: class extends self.ISpriteInstance {},
	Player2HeadFront: class extends self.ISpriteInstance {},
	PlayerHeadP3: class extends self.ISpriteInstance {},
	PlayerHeadP4: class extends self.ISpriteInstance {},
	PlayerHeadP5: class extends self.ISpriteInstance {},
	PlayerHeadP6: class extends self.ISpriteInstance {},
	RealPLayer1: class extends self.ISpriteInstance {},
	RealPLayer2: class extends self.ISpriteInstance {},
	GoalLimit: class extends self.ISpriteInstance {},
	GoalscoreP1: class extends self.ISpriteInstance {},
	GoalscoreP2: class extends self.ISpriteInstance {},
	FieldLimit: class extends self.ISpriteInstance {},
	FloorSolid: class extends self.ISpriteInstance {},
	ColorParticlesBlue: class extends self.IParticlesInstance {},
	ColorParticlesGreen: class extends self.IParticlesInstance {},
	ColorParticlesLight: class extends self.IParticlesInstance {},
	ColorParticlesPink: class extends self.IParticlesInstance {},
	ColorParticlesRed: class extends self.IParticlesInstance {},
	ColorParticlesYellow: class extends self.IParticlesInstance {},
	P1LoseScoreFont: class extends self.ISpriteFontInstance {},
	P1Scorefont: class extends self.ISpriteFontInstance {},
	P1WinScoreFont: class extends self.ISpriteFontInstance {},
	P2LoseScoreFont: class extends self.ISpriteFontInstance {},
	P2Scorefont: class extends self.ISpriteFontInstance {},
	P2WinScoreFont: class extends self.ISpriteFontInstance {},
	MatchTimeFont: class extends self.ISpriteFontInstance {},
	GameTittle: class extends self.ISpriteInstance {},
	GameTittle2: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	light: class extends self.ISpriteInstance {},
	deco: class extends self.ISpriteInstance {},
	menu_ball: class extends self.ISpriteInstance {},
	FadeScreen: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	SmokeParticles: class extends self.IParticlesInstance {},
	SmokeParticles2: class extends self.IParticlesInstance {},
	MoreGameButton: class extends self.IButtonInstance {},
	RestartButton: class extends self.IButtonInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	Player2Shadow: class extends self.ISpriteInstance {},
	PlayersBoard: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	DifficultUI: class extends self.ISpriteInstance {},
	WinScreenFloor: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Family1: class extends self.ISpriteInstance {}
}