const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Physics,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Behaviors.scrollto,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.bound,
		C3.Plugins.Particles,
		C3.Plugins.NinePatch,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.wrap,
		C3.Behaviors.Rotate,
		C3.Plugins.Text,
		C3.Plugins.Timeline,
		C3.Behaviors.Platform,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.NinePatch.Exps.Angle,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.JavaScriptInEvents.E_game_Event74_Act2,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{BodyPlayer: 0},
	{BulletCount: 0},
	{PlayerGun: 0},
	{AllSkins: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Physics: 0},
	{Fade: 0},
	{Fade2: 0},
	{FlashGun: 0},
	{LineAim: 0},
	{Aim: 0},
	{Limit: 0},
	{Sine: 0},
	{Money_collect: 0},
	{hero11_: 0},
	{hero12_: 0},
	{Hud_Bullet: 0},
	{HudTextInfo: 0},
	{NoThanks: 0},
	{BlackScreen: 0},
	{BlackScreen2: 0},
	{Hud_paused: 0},
	{Hud_Money1: 0},
	{LevelComplete: 0},
	{LevelFinal: 0},
	{Boss: 0},
	{Levels_Hud: 0},
	{BossHud: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{SaveGame: 0},
	{Keyboard: 0},
	{Browser: 0},
	{ScrollTo: 0},
	{Cam: 0},
	{Audio: 0},
	{Gamelogo: 0},
	{Logo: 0},
	{Video: 0},
	{HeadEnemies: 0},
	{BodyEnemies: 0},
	{BoundToLayout: 0},
	{Txt_DestroyEnemieBody: 0},
	{Txt_DestroyEnemieHead: 0},
	{Alvos: 0},
	{EnemExplosion: 0},
	{Explosion: 0},
	{BoxMetal: 0},
	{Particles: 0},
	{Solid: 0},
	{Wood: 0},
	{Metal: 0},
	{Acid_Lava: 0},
	{Spike: 0},
	{Particle_Smoke: 0},
	{Tiled64x: 0},
	{Tilemap32x: 0},
	{Background: 0},
	{BackgroundLevelSelect: 0},
	{Bt_2x: 0},
	{Pin: 0},
	{bt_home: 0},
	{bt_levels: 0},
	{bt_pause: 0},
	{Bt_restartnoammo: 0},
	{bt_restat: 0},
	{bt_moregames: 0},
	{bt_shop: 0},
	{bt_home1: 0},
	{bt_buy: 0},
	{Bt_play: 0},
	{Bt_startgame: 0},
	{bt_nextskin: 0},
	{bt_FullScreen: 0},
	{Level_selec_HUD: 0},
	{Level: 0},
	{LevelButton: 0},
	{Particles_Blood: 0},
	{Particles_Money: 0},
	{Type: 0},
	{FontText: 0},
	{FontText2: 0},
	{Tutorial2: 0},
	{AJAX: 0},
	{JSON: 0},
	{Sprite10: 0},
	{Sprite5: 0},
	{Sprite7: 0},
	{Sprite9: 0},
	{Box: 0},
	{Wrap: 0},
	{Cloud: 0},
	{Cloud1: 0},
	{Cloud2: 0},
	{enemies_animation: 0},
	{logoGl: 0},
	{Sky: 0},
	{Sprite: 0},
	{Rotate: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Text: 0},
	{Tile: 0},
	{Tile1: 0},
	{Tile2: 0},
	{TimelineController: 0},
	{Transition: 0},
	{Transition2: 0},
	{Tree: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{Tutorial: 0},
	{rightarrow: 0},
	{HowToPlay_btn: 0},
	{Skip: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{Platform: 0},
	{TargetsBody: 0},
	{TargetsHead: 0},
	{Skins: 0},
	{TouchCount: 0},
	{Pause: 0},
	{Money: 0},
	{MoneyTotal: 0},
	{InterShow: 0},
	{FullScreen: 0},
	{SkinAtual: 0},
	{SkinSelect: 0}
];

self.InstanceType = {
	BodyPlayer: class extends self.ISpriteInstance {},
	PlayerGun: class extends self.ISpriteInstance {},
	AllSkins: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	FlashGun: class extends self.ISpriteInstance {},
	LineAim: class extends self.ISpriteInstance {},
	Aim: class extends self.ISpriteInstance {},
	Limit: class extends self.ISpriteInstance {},
	Money_collect: class extends self.ISpriteInstance {},
	hero11_: class extends self.ISpriteInstance {},
	hero12_: class extends self.ISpriteInstance {},
	Hud_Bullet: class extends self.ISpriteInstance {},
	HudTextInfo: class extends self.ISpriteInstance {},
	NoThanks: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	BlackScreen2: class extends self.ISpriteInstance {},
	Hud_paused: class extends self.ISpriteInstance {},
	Hud_Money1: class extends self.ISpriteInstance {},
	Levels_Hud: class extends self.ISpriteInstance {},
	BossHud: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SaveGame: class extends self.IArrayInstance {},
	Fade: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Cam: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Gamelogo: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	HeadEnemies: class extends self.ISpriteInstance {},
	BodyEnemies: class extends self.ISpriteInstance {},
	Txt_DestroyEnemieBody: class extends self.ISpriteInstance {},
	Txt_DestroyEnemieHead: class extends self.ISpriteInstance {},
	Alvos: class extends self.ISpriteInstance {},
	EnemExplosion: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	BoxMetal: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Wood: class extends self.IWorldInstance {},
	Metal: class extends self.IWorldInstance {},
	Acid_Lava: class extends self.ISpriteInstance {},
	Spike: class extends self.ITiledBackgroundInstance {},
	Boss: class extends self.ISpriteInstance {},
	Particle_Smoke: class extends self.IParticlesInstance {},
	Tiled64x: class extends self.ITilemapInstance {},
	Tilemap32x: class extends self.ITilemapInstance {},
	Background: class extends self.ISpriteInstance {},
	BackgroundLevelSelect: class extends self.ISpriteInstance {},
	Bt_2x: class extends self.ISpriteInstance {},
	bt_home: class extends self.ISpriteInstance {},
	bt_levels: class extends self.ISpriteInstance {},
	bt_pause: class extends self.ISpriteInstance {},
	Bt_restartnoammo: class extends self.ISpriteInstance {},
	bt_restat: class extends self.ISpriteInstance {},
	bt_moregames: class extends self.ISpriteInstance {},
	bt_shop: class extends self.ISpriteInstance {},
	bt_home1: class extends self.ISpriteInstance {},
	bt_buy: class extends self.ISpriteInstance {},
	Bt_play: class extends self.ISpriteInstance {},
	Bt_startgame: class extends self.ISpriteInstance {},
	bt_nextskin: class extends self.ISpriteInstance {},
	bt_FullScreen: class extends self.ISpriteInstance {},
	Level_selec_HUD: class extends self.ISpriteInstance {},
	LevelButton: class extends self.ISpriteInstance {},
	Particles_Blood: class extends self.IParticlesInstance {},
	Particles_Money: class extends self.IParticlesInstance {},
	FontText: class extends self.ISpriteFontInstance {},
	FontText2: class extends self.ISpriteFontInstance {},
	Tutorial2: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Cloud: class extends self.ISpriteInstance {},
	Cloud1: class extends self.ISpriteInstance {},
	Cloud2: class extends self.ISpriteInstance {},
	enemies_animation: class extends self.ISpriteInstance {},
	logoGl: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Tile: class extends self.ISpriteInstance {},
	Tile1: class extends self.ISpriteInstance {},
	Tile2: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Transition: class extends self.ISpriteInstance {},
	Transition2: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ISpriteInstance {},
	rightarrow: class extends self.ISpriteInstance {},
	HowToPlay_btn: class extends self.ISpriteInstance {},
	Skip: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	TargetsBody: class extends self.ISpriteInstance {},
	TargetsHead: class extends self.ISpriteInstance {},
	Skins: class extends self.ISpriteInstance {}
}