const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.advert,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Audio,
		C3.Plugins.Sprite,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.TextBox,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.Gamecode_Event11_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Spritefont2.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Pin.Acts.SetDestroy,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Exps.viewportleft,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Particles.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Cnds.OnCreated,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnProgress,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.Json.Exps.CurrentValue,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{type: 0},
	{cardUID: 0},
	{SpriteFont: 0},
	{Browser: 0},
	{JSON: 0},
	{AJAX: 0},
	{levelCode: 0},
	{LocalStorage: 0},
	{shuffleArrayFirst: 0},
	{shuffleArrayShuffled: 0},
	{MobileAdvert: 0},
	{PlatformInfo: 0},
	{Audio: 0},
	{btnMain: 0},
	{btnContinue: 0},
	{btnHome: 0},
	{btnPlay: 0},
	{btnTryAgain: 0},
	{btnBack: 0},
	{btnExitSettings: 0},
	{btnResetData: 0},
	{modePrev: 0},
	{btnSettings: 0},
	{btnSound: 0},
	{btnStore: 0},
	{btnUnlockRandom: 0},
	{JSON2: 0},
	{background: 0},
	{starParticle: 0},
	{Tween: 0},
	{Timer: 0},
	{starParticleSprite: 0},
	{number: 0},
	{drag: 0},
	{xStart: 0},
	{yStart: 0},
	{widthStart: 0},
	{heightStart: 0},
	{cardUnder: 0},
	{card: 0},
	{num: 0},
	{cardMainBg: 0},
	{fade: 0},
	{game: 0},
	{frame: 0},
	{cardAddParticle: 0},
	{cardAddParticleSprite: 0},
	{occupied: 0},
	{hold: 0},
	{Sine: 0},
	{tutorialHand: 0},
	{mode: 0},
	{cardAlarm: 0},
	{diamond: 0},
	{border: 0},
	{TextInput: 0},
	{storeCardSet: 0},
	{logo: 0},
	{storeSelect: 0},
	{trash: 0},
	{winParticleSprite: 0},
	{winParticle: 0},
	{"9patch": 0},
	{storeCardSetBg: 0},
	{btnWinLoseText: 0},
	{btnInfo: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{Video: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{Keyboard: 0},
	{Sprite4: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Pin: 0},
	{fSpriteFont: 0},
	{fCard: 0},
	{fDiamond: 0},
	{fCardHolder: 0},
	{fStoreCardSet: 0},
	{vMode: 0},
	{ShuffledWords: 0},
	{pick: 0},
	{Values: 0},
	{vCardsCount: 0},
	{vTokenCard: 0},
	{vSkipNum: 0},
	{vLevelCodeNumMax: 0},
	{vCardLeft: 0},
	{vDiamondUID: 0},
	{hasTop: 0},
	{vFrontCards: 0},
	{vDiceSpecial: 0},
	{vPositiveCards: 0},
	{vDiceBalance: 0},
	{vCardUID: 0},
	{vDo: 0},
	{vNumber: 0},
	{vDice: 0},
	{vBrightness: 0},
	{vTweenTime: 0},
	{vTweenFadeTime: 0},
	{level: 0},
	{levelCodeToken: 0},
	{levelCodeNum: 0},
	{diamondWin: 0},
	{numberMin: 0},
	{numberMax: 0},
	{trashPrice: 0},
	{cardSetSelectedFrame: 0},
	{storeCardSetPrice: 0},
	{storeCardSetToken: 0},
	{sound: 0},
	{touchDX: 0},
	{touchDY: 0},
	{cardUidTouch: 0},
	{tutorial: 0},
	{gameCheckWinLoseTimer: 0},
	{cardWidth: 0},
	{cardHeight: 0},
	{json: 0},
	{jsonLocation: 0},
	{jsonUrl: 0},
	{vToken: 0},
	{vLevelNum: 0},
	{vLevelCode: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Browser: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	AJAX: class extends self.IInstance {},
	levelCode: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	shuffleArrayFirst: class extends self.IArrayInstance {},
	shuffleArrayShuffled: class extends self.IArrayInstance {},
	MobileAdvert: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	btnMain: class extends self.ISpriteInstance {},
	btnContinue: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnTryAgain: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	btnExitSettings: class extends self.ISpriteInstance {},
	btnResetData: class extends self.ISpriteInstance {},
	btnSettings: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	btnStore: class extends self.ISpriteInstance {},
	btnUnlockRandom: class extends self.ISpriteInstance {},
	JSON2: class extends self.IJSONInstance {},
	background: class extends self.ISpriteInstance {},
	starParticle: class extends self.IParticlesInstance {},
	starParticleSprite: class extends self.ISpriteInstance {},
	card: class extends self.ISpriteInstance {},
	cardMainBg: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	game: class extends self.ISpriteInstance {},
	cardAddParticle: class extends self.IParticlesInstance {},
	cardAddParticleSprite: class extends self.ISpriteInstance {},
	hold: class extends self.ISpriteInstance {},
	tutorialHand: class extends self.ISpriteInstance {},
	cardAlarm: class extends self.ISpriteInstance {},
	diamond: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	storeCardSet: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	storeSelect: class extends self.ISpriteInstance {},
	trash: class extends self.ISpriteInstance {},
	winParticleSprite: class extends self.ISpriteInstance {},
	winParticle: class extends self.IParticlesInstance {},
	_9patch: class extends self.IWorldInstance {},
	storeCardSetBg: class extends self.ISpriteInstance {},
	btnWinLoseText: class extends self.ISpriteInstance {},
	btnInfo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	fSpriteFont: class extends self.ISpriteFontInstance {},
	fCard: class extends self.ISpriteInstance {},
	fDiamond: class extends self.ISpriteInstance {},
	fCardHolder: class extends self.ISpriteInstance {},
	fStoreCardSet: class extends self.ISpriteInstance {}
}