const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.DragnDrop.Cnds.IsEnabled,
		C3.JavaScriptInEvents.Egame_Event9_Act1,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{BackgroundMenu: 0},
	{SelfX: 0},
	{SelfY: 0},
	{Sine: 0},
	{LogoGame: 0},
	{btnPlay: 0},
	{btnFullscreen: 0},
	{btnMusic: 0},
	{PuzzleLogoMenu1: 0},
	{PuzzleLogoMenu2: 0},
	{PuzzleLogoMenu3: 0},
	{PuzzleLogoMenu4: 0},
	{PuzzleLogoMenu5: 0},
	{PuzzleLogoMenu6: 0},
	{PuzzleLogoMenu7: 0},
	{elips: 0},
	{Orbit: 0},
	{slide: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Touch: 0},
	{SpriteFont: 0},
	{BoardLevels: 0},
	{bgSlider: 0},
	{DragDrop: 0},
	{slider: 0},
	{Num: 0},
	{btnLv1: 0},
	{btnLv10: 0},
	{btnLv11: 0},
	{btnLv12: 0},
	{btnLv13: 0},
	{btnLv14: 0},
	{btnLv15: 0},
	{btnLv16: 0},
	{btnLv17: 0},
	{btnLv18: 0},
	{btnLv19: 0},
	{btnLv2: 0},
	{btnLv20: 0},
	{btnLv21: 0},
	{btnLv22: 0},
	{btnLv23: 0},
	{btnLv24: 0},
	{btnLv3: 0},
	{btnLv4: 0},
	{btnLv5: 0},
	{btnLv6: 0},
	{btnLv7: 0},
	{btnLv8: 0},
	{btnLv9: 0},
	{Sprite: 0},
	{y_start: 0},
	{Path: 0},
	{MoveTo: 0},
	{dragdrop_obj: 0},
	{btnHome: 0},
	{Pin: 0},
	{LogoBlock: 0},
	{NeedX: 0},
	{NeedY: 0},
	{StartX: 0},
	{StartY: 0},
	{ElementLevel11: 0},
	{ElementLevel12: 0},
	{ElementLevel13: 0},
	{ElementLevel14: 0},
	{ElementLevel15: 0},
	{ElementLevel16: 0},
	{PictureLevel1: 0},
	{ElementLevel21: 0},
	{ElementLevel22: 0},
	{ElementLevel23: 0},
	{ElementLevel24: 0},
	{PictureLevel2: 0},
	{ElementLevel31: 0},
	{ElementLevel32: 0},
	{ElementLevel33: 0},
	{ElementLevel34: 0},
	{PictureLevel3: 0},
	{ElementLevel41: 0},
	{ElementLevel42: 0},
	{ElementLevel43: 0},
	{ElementLevel44: 0},
	{PictureLevel4: 0},
	{ElementLevel51: 0},
	{ElementLevel52: 0},
	{ElementLevel53: 0},
	{ElementLevel54: 0},
	{PictureLevel5: 0},
	{ElementLevel61: 0},
	{ElementLevel62: 0},
	{ElementLevel63: 0},
	{ElementLevel64: 0},
	{ElementLevel65: 0},
	{ElementLevel66: 0},
	{PictureLevel6: 0},
	{ElementLevel71: 0},
	{ElementLevel72: 0},
	{ElementLevel73: 0},
	{ElementLevel74: 0},
	{ElementLevel75: 0},
	{ElementLevel76: 0},
	{ElementLevel77: 0},
	{PictureLevel7: 0},
	{ElementLevel81: 0},
	{ElementLevel82: 0},
	{ElementLevel83: 0},
	{ElementLevel84: 0},
	{ElementLevel85: 0},
	{ElementLevel86: 0},
	{ElementLevel87: 0},
	{ElementLevel88: 0},
	{PictureLevel8: 0},
	{ElementLevel91: 0},
	{ElementLevel92: 0},
	{ElementLevel93: 0},
	{ElementLevel94: 0},
	{ElementLevel95: 0},
	{ElementLevel96: 0},
	{ElementLevel97: 0},
	{PictureLevel9: 0},
	{ElementLevel910: 0},
	{ElementLevel101: 0},
	{ElementLevel102: 0},
	{ElementLevel103: 0},
	{ElementLevel104: 0},
	{ElementLevel105: 0},
	{ElementLevel106: 0},
	{ElementLevel107: 0},
	{ElementLevel108: 0},
	{PictureLevel10: 0},
	{ElementLevel111: 0},
	{ElementLevel112: 0},
	{ElementLevel113: 0},
	{ElementLevel114: 0},
	{ElementLevel115: 0},
	{ElementLevel116: 0},
	{ElementLevel117: 0},
	{ElementLevel118: 0},
	{PictureLevel11: 0},
	{ElementLevel121: 0},
	{ElementLevel122: 0},
	{ElementLevel123: 0},
	{ElementLevel124: 0},
	{ElementLevel125: 0},
	{ElementLevel126: 0},
	{ElementLevel127: 0},
	{ElementLevel128: 0},
	{PictureLevel12: 0},
	{ElementLevel131: 0},
	{ElementLevel132: 0},
	{ElementLevel133: 0},
	{ElementLevel134: 0},
	{ElementLevel135: 0},
	{ElementLevel136: 0},
	{ElementLevel137: 0},
	{ElementLevel138: 0},
	{ElementLevel139: 0},
	{PictureLevel13: 0},
	{ElementLevel141: 0},
	{ElementLevel142: 0},
	{ElementLevel143: 0},
	{ElementLevel144: 0},
	{ElementLevel145: 0},
	{ElementLevel146: 0},
	{ElementLevel147: 0},
	{ElementLevel148: 0},
	{PictureLevel14: 0},
	{ElementLevel151: 0},
	{ElementLevel152: 0},
	{ElementLevel153: 0},
	{ElementLevel154: 0},
	{ElementLevel155: 0},
	{ElementLevel156: 0},
	{ElementLevel157: 0},
	{ElementLevel158: 0},
	{PictureLevel15: 0},
	{ElementLevel159: 0},
	{ElementLevel161: 0},
	{ElementLevel162: 0},
	{ElementLevel163: 0},
	{ElementLevel164: 0},
	{ElementLevel165: 0},
	{ElementLevel166: 0},
	{ElementLevel167: 0},
	{ElementLevel168: 0},
	{PictureLevel16: 0},
	{ElementLevel171: 0},
	{ElementLevel1710: 0},
	{ElementLevel172: 0},
	{ElementLevel173: 0},
	{ElementLevel174: 0},
	{ElementLevel175: 0},
	{ElementLevel176: 0},
	{ElementLevel177: 0},
	{ElementLevel178: 0},
	{ElementLevel179: 0},
	{PictureLevel17: 0},
	{ElementLevel181: 0},
	{ElementLevel1810: 0},
	{ElementLevel1811: 0},
	{ElementLevel182: 0},
	{ElementLevel183: 0},
	{ElementLevel184: 0},
	{ElementLevel185: 0},
	{ElementLevel186: 0},
	{ElementLevel187: 0},
	{ElementLevel188: 0},
	{PictureLevel189: 0},
	{ElementLevel191: 0},
	{ElementLevel1910: 0},
	{ElementLevel192: 0},
	{ElementLevel193: 0},
	{ElementLevel194: 0},
	{ElementLevel195: 0},
	{ElementLevel196: 0},
	{ElementLevel197: 0},
	{ElementLevel198: 0},
	{PictureLevel19: 0},
	{ElementLevel1911: 0},
	{ElementLevel201: 0},
	{ElementLevel2010: 0},
	{ElementLevel202: 0},
	{ElementLevel203: 0},
	{ElementLevel204: 0},
	{ElementLevel205: 0},
	{ElementLevel206: 0},
	{ElementLevel207: 0},
	{ElementLevel208: 0},
	{ElementLevel209: 0},
	{PictureLevel20: 0},
	{ElementLevel211: 0},
	{ElementLevel2110: 0},
	{ElementLevel2111: 0},
	{ElementLevel2112: 0},
	{ElementLevel212: 0},
	{ElementLevel213: 0},
	{ElementLevel214: 0},
	{ElementLevel216: 0},
	{ElementLevel217: 0},
	{ElementLevel218: 0},
	{ElementLevel219: 0},
	{PictureLevel21: 0},
	{ElementLevel231: 0},
	{ElementLevel2310: 0},
	{ElementLevel2311: 0},
	{ElementLevel2312: 0},
	{ElementLevel232: 0},
	{ElementLevel233: 0},
	{ElementLevel234: 0},
	{ElementLevel235: 0},
	{ElementLevel236: 0},
	{ElementLevel237: 0},
	{ElementLevel238: 0},
	{ElementLevel239: 0},
	{PictureLevel23: 0},
	{ElementLevel241: 0},
	{ElementLevel2410: 0},
	{ElementLevel242: 0},
	{ElementLevel243: 0},
	{ElementLevel244: 0},
	{ElementLevel245: 0},
	{ElementLevel246: 0},
	{ElementLevel247: 0},
	{ElementLevel248: 0},
	{ElementLevel249: 0},
	{PictureLevel24: 0},
	{ElementLevel251: 0},
	{ElementLevel2510: 0},
	{ElementLevel2511: 0},
	{ElementLevel2512: 0},
	{ElementLevel252: 0},
	{ElementLevel253: 0},
	{ElementLevel254: 0},
	{ElementLevel255: 0},
	{ElementLevel256: 0},
	{ElementLevel257: 0},
	{ElementLevel258: 0},
	{ElementLevel259: 0},
	{PictureLevel25: 0},
	{Tween: 0},
	{BoardGame: 0},
	{BoardWin: 0},
	{btnOverHome: 0},
	{btnOverNext: 0},
	{loader_bg: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{button: 0},
	{Sine2: 0},
	{PuzzleLogo: 0},
	{Levels: 0},
	{Elements: 0},
	{Picture: 0},
	{UnlockLevel: 0},
	{CurrentLevel: 0},
	{scroll: 0},
	{scrollC: 0},
	{scrollM: 0},
	{scrollS: 0}
];

self.InstanceType = {
	BackgroundMenu: class extends self.ITiledBackgroundInstance {},
	LogoGame: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnMusic: class extends self.ISpriteInstance {},
	PuzzleLogoMenu1: class extends self.ISpriteInstance {},
	PuzzleLogoMenu2: class extends self.ISpriteInstance {},
	PuzzleLogoMenu3: class extends self.ISpriteInstance {},
	PuzzleLogoMenu4: class extends self.ISpriteInstance {},
	PuzzleLogoMenu5: class extends self.ISpriteInstance {},
	PuzzleLogoMenu6: class extends self.ISpriteInstance {},
	PuzzleLogoMenu7: class extends self.ISpriteInstance {},
	elips: class extends self.ISpriteInstance {},
	slide: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	BoardLevels: class extends self.ISpriteInstance {},
	bgSlider: class extends self.ISpriteInstance {},
	slider: class extends self.ISpriteInstance {},
	btnLv1: class extends self.ISpriteInstance {},
	btnLv10: class extends self.ISpriteInstance {},
	btnLv11: class extends self.ISpriteInstance {},
	btnLv12: class extends self.ISpriteInstance {},
	btnLv13: class extends self.ISpriteInstance {},
	btnLv14: class extends self.ISpriteInstance {},
	btnLv15: class extends self.ISpriteInstance {},
	btnLv16: class extends self.ISpriteInstance {},
	btnLv17: class extends self.ISpriteInstance {},
	btnLv18: class extends self.ISpriteInstance {},
	btnLv19: class extends self.ISpriteInstance {},
	btnLv2: class extends self.ISpriteInstance {},
	btnLv20: class extends self.ISpriteInstance {},
	btnLv21: class extends self.ISpriteInstance {},
	btnLv22: class extends self.ISpriteInstance {},
	btnLv23: class extends self.ISpriteInstance {},
	btnLv24: class extends self.ISpriteInstance {},
	btnLv3: class extends self.ISpriteInstance {},
	btnLv4: class extends self.ISpriteInstance {},
	btnLv5: class extends self.ISpriteInstance {},
	btnLv6: class extends self.ISpriteInstance {},
	btnLv7: class extends self.ISpriteInstance {},
	btnLv8: class extends self.ISpriteInstance {},
	btnLv9: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	dragdrop_obj: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	LogoBlock: class extends self.ISpriteInstance {},
	ElementLevel11: class extends self.ISpriteInstance {},
	ElementLevel12: class extends self.ISpriteInstance {},
	ElementLevel13: class extends self.ISpriteInstance {},
	ElementLevel14: class extends self.ISpriteInstance {},
	ElementLevel15: class extends self.ISpriteInstance {},
	ElementLevel16: class extends self.ISpriteInstance {},
	PictureLevel1: class extends self.ISpriteInstance {},
	ElementLevel21: class extends self.ISpriteInstance {},
	ElementLevel22: class extends self.ISpriteInstance {},
	ElementLevel23: class extends self.ISpriteInstance {},
	ElementLevel24: class extends self.ISpriteInstance {},
	PictureLevel2: class extends self.ISpriteInstance {},
	ElementLevel31: class extends self.ISpriteInstance {},
	ElementLevel32: class extends self.ISpriteInstance {},
	ElementLevel33: class extends self.ISpriteInstance {},
	ElementLevel34: class extends self.ISpriteInstance {},
	PictureLevel3: class extends self.ISpriteInstance {},
	ElementLevel41: class extends self.ISpriteInstance {},
	ElementLevel42: class extends self.ISpriteInstance {},
	ElementLevel43: class extends self.ISpriteInstance {},
	ElementLevel44: class extends self.ISpriteInstance {},
	PictureLevel4: class extends self.ISpriteInstance {},
	ElementLevel51: class extends self.ISpriteInstance {},
	ElementLevel52: class extends self.ISpriteInstance {},
	ElementLevel53: class extends self.ISpriteInstance {},
	ElementLevel54: class extends self.ISpriteInstance {},
	PictureLevel5: class extends self.ISpriteInstance {},
	ElementLevel61: class extends self.ISpriteInstance {},
	ElementLevel62: class extends self.ISpriteInstance {},
	ElementLevel63: class extends self.ISpriteInstance {},
	ElementLevel64: class extends self.ISpriteInstance {},
	ElementLevel65: class extends self.ISpriteInstance {},
	ElementLevel66: class extends self.ISpriteInstance {},
	PictureLevel6: class extends self.ISpriteInstance {},
	ElementLevel71: class extends self.ISpriteInstance {},
	ElementLevel72: class extends self.ISpriteInstance {},
	ElementLevel73: class extends self.ISpriteInstance {},
	ElementLevel74: class extends self.ISpriteInstance {},
	ElementLevel75: class extends self.ISpriteInstance {},
	ElementLevel76: class extends self.ISpriteInstance {},
	ElementLevel77: class extends self.ISpriteInstance {},
	PictureLevel7: class extends self.ISpriteInstance {},
	ElementLevel81: class extends self.ISpriteInstance {},
	ElementLevel82: class extends self.ISpriteInstance {},
	ElementLevel83: class extends self.ISpriteInstance {},
	ElementLevel84: class extends self.ISpriteInstance {},
	ElementLevel85: class extends self.ISpriteInstance {},
	ElementLevel86: class extends self.ISpriteInstance {},
	ElementLevel87: class extends self.ISpriteInstance {},
	ElementLevel88: class extends self.ISpriteInstance {},
	PictureLevel8: class extends self.ISpriteInstance {},
	ElementLevel91: class extends self.ISpriteInstance {},
	ElementLevel92: class extends self.ISpriteInstance {},
	ElementLevel93: class extends self.ISpriteInstance {},
	ElementLevel94: class extends self.ISpriteInstance {},
	ElementLevel95: class extends self.ISpriteInstance {},
	ElementLevel96: class extends self.ISpriteInstance {},
	ElementLevel97: class extends self.ISpriteInstance {},
	PictureLevel9: class extends self.ISpriteInstance {},
	ElementLevel910: class extends self.ISpriteInstance {},
	ElementLevel101: class extends self.ISpriteInstance {},
	ElementLevel102: class extends self.ISpriteInstance {},
	ElementLevel103: class extends self.ISpriteInstance {},
	ElementLevel104: class extends self.ISpriteInstance {},
	ElementLevel105: class extends self.ISpriteInstance {},
	ElementLevel106: class extends self.ISpriteInstance {},
	ElementLevel107: class extends self.ISpriteInstance {},
	ElementLevel108: class extends self.ISpriteInstance {},
	PictureLevel10: class extends self.ISpriteInstance {},
	ElementLevel111: class extends self.ISpriteInstance {},
	ElementLevel112: class extends self.ISpriteInstance {},
	ElementLevel113: class extends self.ISpriteInstance {},
	ElementLevel114: class extends self.ISpriteInstance {},
	ElementLevel115: class extends self.ISpriteInstance {},
	ElementLevel116: class extends self.ISpriteInstance {},
	ElementLevel117: class extends self.ISpriteInstance {},
	ElementLevel118: class extends self.ISpriteInstance {},
	PictureLevel11: class extends self.ISpriteInstance {},
	ElementLevel121: class extends self.ISpriteInstance {},
	ElementLevel122: class extends self.ISpriteInstance {},
	ElementLevel123: class extends self.ISpriteInstance {},
	ElementLevel124: class extends self.ISpriteInstance {},
	ElementLevel125: class extends self.ISpriteInstance {},
	ElementLevel126: class extends self.ISpriteInstance {},
	ElementLevel127: class extends self.ISpriteInstance {},
	ElementLevel128: class extends self.ISpriteInstance {},
	PictureLevel12: class extends self.ISpriteInstance {},
	ElementLevel131: class extends self.ISpriteInstance {},
	ElementLevel132: class extends self.ISpriteInstance {},
	ElementLevel133: class extends self.ISpriteInstance {},
	ElementLevel134: class extends self.ISpriteInstance {},
	ElementLevel135: class extends self.ISpriteInstance {},
	ElementLevel136: class extends self.ISpriteInstance {},
	ElementLevel137: class extends self.ISpriteInstance {},
	ElementLevel138: class extends self.ISpriteInstance {},
	ElementLevel139: class extends self.ISpriteInstance {},
	PictureLevel13: class extends self.ISpriteInstance {},
	ElementLevel141: class extends self.ISpriteInstance {},
	ElementLevel142: class extends self.ISpriteInstance {},
	ElementLevel143: class extends self.ISpriteInstance {},
	ElementLevel144: class extends self.ISpriteInstance {},
	ElementLevel145: class extends self.ISpriteInstance {},
	ElementLevel146: class extends self.ISpriteInstance {},
	ElementLevel147: class extends self.ISpriteInstance {},
	ElementLevel148: class extends self.ISpriteInstance {},
	PictureLevel14: class extends self.ISpriteInstance {},
	ElementLevel151: class extends self.ISpriteInstance {},
	ElementLevel152: class extends self.ISpriteInstance {},
	ElementLevel153: class extends self.ISpriteInstance {},
	ElementLevel154: class extends self.ISpriteInstance {},
	ElementLevel155: class extends self.ISpriteInstance {},
	ElementLevel156: class extends self.ISpriteInstance {},
	ElementLevel157: class extends self.ISpriteInstance {},
	ElementLevel158: class extends self.ISpriteInstance {},
	PictureLevel15: class extends self.ISpriteInstance {},
	ElementLevel159: class extends self.ISpriteInstance {},
	ElementLevel161: class extends self.ISpriteInstance {},
	ElementLevel162: class extends self.ISpriteInstance {},
	ElementLevel163: class extends self.ISpriteInstance {},
	ElementLevel164: class extends self.ISpriteInstance {},
	ElementLevel165: class extends self.ISpriteInstance {},
	ElementLevel166: class extends self.ISpriteInstance {},
	ElementLevel167: class extends self.ISpriteInstance {},
	ElementLevel168: class extends self.ISpriteInstance {},
	PictureLevel16: class extends self.ISpriteInstance {},
	ElementLevel171: class extends self.ISpriteInstance {},
	ElementLevel1710: class extends self.ISpriteInstance {},
	ElementLevel172: class extends self.ISpriteInstance {},
	ElementLevel173: class extends self.ISpriteInstance {},
	ElementLevel174: class extends self.ISpriteInstance {},
	ElementLevel175: class extends self.ISpriteInstance {},
	ElementLevel176: class extends self.ISpriteInstance {},
	ElementLevel177: class extends self.ISpriteInstance {},
	ElementLevel178: class extends self.ISpriteInstance {},
	ElementLevel179: class extends self.ISpriteInstance {},
	PictureLevel17: class extends self.ISpriteInstance {},
	ElementLevel181: class extends self.ISpriteInstance {},
	ElementLevel1810: class extends self.ISpriteInstance {},
	ElementLevel1811: class extends self.ISpriteInstance {},
	ElementLevel182: class extends self.ISpriteInstance {},
	ElementLevel183: class extends self.ISpriteInstance {},
	ElementLevel184: class extends self.ISpriteInstance {},
	ElementLevel185: class extends self.ISpriteInstance {},
	ElementLevel186: class extends self.ISpriteInstance {},
	ElementLevel187: class extends self.ISpriteInstance {},
	ElementLevel188: class extends self.ISpriteInstance {},
	PictureLevel189: class extends self.ISpriteInstance {},
	ElementLevel191: class extends self.ISpriteInstance {},
	ElementLevel1910: class extends self.ISpriteInstance {},
	ElementLevel192: class extends self.ISpriteInstance {},
	ElementLevel193: class extends self.ISpriteInstance {},
	ElementLevel194: class extends self.ISpriteInstance {},
	ElementLevel195: class extends self.ISpriteInstance {},
	ElementLevel196: class extends self.ISpriteInstance {},
	ElementLevel197: class extends self.ISpriteInstance {},
	ElementLevel198: class extends self.ISpriteInstance {},
	PictureLevel19: class extends self.ISpriteInstance {},
	ElementLevel1911: class extends self.ISpriteInstance {},
	ElementLevel201: class extends self.ISpriteInstance {},
	ElementLevel2010: class extends self.ISpriteInstance {},
	ElementLevel202: class extends self.ISpriteInstance {},
	ElementLevel203: class extends self.ISpriteInstance {},
	ElementLevel204: class extends self.ISpriteInstance {},
	ElementLevel205: class extends self.ISpriteInstance {},
	ElementLevel206: class extends self.ISpriteInstance {},
	ElementLevel207: class extends self.ISpriteInstance {},
	ElementLevel208: class extends self.ISpriteInstance {},
	ElementLevel209: class extends self.ISpriteInstance {},
	PictureLevel20: class extends self.ISpriteInstance {},
	ElementLevel211: class extends self.ISpriteInstance {},
	ElementLevel2110: class extends self.ISpriteInstance {},
	ElementLevel2111: class extends self.ISpriteInstance {},
	ElementLevel2112: class extends self.ISpriteInstance {},
	ElementLevel212: class extends self.ISpriteInstance {},
	ElementLevel213: class extends self.ISpriteInstance {},
	ElementLevel214: class extends self.ISpriteInstance {},
	ElementLevel216: class extends self.ISpriteInstance {},
	ElementLevel217: class extends self.ISpriteInstance {},
	ElementLevel218: class extends self.ISpriteInstance {},
	ElementLevel219: class extends self.ISpriteInstance {},
	PictureLevel21: class extends self.ISpriteInstance {},
	ElementLevel231: class extends self.ISpriteInstance {},
	ElementLevel2310: class extends self.ISpriteInstance {},
	ElementLevel2311: class extends self.ISpriteInstance {},
	ElementLevel2312: class extends self.ISpriteInstance {},
	ElementLevel232: class extends self.ISpriteInstance {},
	ElementLevel233: class extends self.ISpriteInstance {},
	ElementLevel234: class extends self.ISpriteInstance {},
	ElementLevel235: class extends self.ISpriteInstance {},
	ElementLevel236: class extends self.ISpriteInstance {},
	ElementLevel237: class extends self.ISpriteInstance {},
	ElementLevel238: class extends self.ISpriteInstance {},
	ElementLevel239: class extends self.ISpriteInstance {},
	PictureLevel23: class extends self.ISpriteInstance {},
	ElementLevel241: class extends self.ISpriteInstance {},
	ElementLevel2410: class extends self.ISpriteInstance {},
	ElementLevel242: class extends self.ISpriteInstance {},
	ElementLevel243: class extends self.ISpriteInstance {},
	ElementLevel244: class extends self.ISpriteInstance {},
	ElementLevel245: class extends self.ISpriteInstance {},
	ElementLevel246: class extends self.ISpriteInstance {},
	ElementLevel247: class extends self.ISpriteInstance {},
	ElementLevel248: class extends self.ISpriteInstance {},
	ElementLevel249: class extends self.ISpriteInstance {},
	PictureLevel24: class extends self.ISpriteInstance {},
	ElementLevel251: class extends self.ISpriteInstance {},
	ElementLevel2510: class extends self.ISpriteInstance {},
	ElementLevel2511: class extends self.ISpriteInstance {},
	ElementLevel2512: class extends self.ISpriteInstance {},
	ElementLevel252: class extends self.ISpriteInstance {},
	ElementLevel253: class extends self.ISpriteInstance {},
	ElementLevel254: class extends self.ISpriteInstance {},
	ElementLevel255: class extends self.ISpriteInstance {},
	ElementLevel256: class extends self.ISpriteInstance {},
	ElementLevel257: class extends self.ISpriteInstance {},
	ElementLevel258: class extends self.ISpriteInstance {},
	ElementLevel259: class extends self.ISpriteInstance {},
	PictureLevel25: class extends self.ISpriteInstance {},
	BoardGame: class extends self.ISpriteInstance {},
	BoardWin: class extends self.ISpriteInstance {},
	btnOverHome: class extends self.ISpriteInstance {},
	btnOverNext: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	button: class extends self.ISpriteInstance {},
	PuzzleLogo: class extends self.ISpriteInstance {},
	Levels: class extends self.ISpriteInstance {},
	Elements: class extends self.ISpriteInstance {},
	Picture: class extends self.ISpriteInstance {}
}