const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Plugins.video,
		C3.Plugins.Timeline,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.scrollto,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.System.Exps.layeropacity,
		C3.JavaScriptInEvents.Codegame_Event53_Act1,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{button: 0},
	{SpriteFont: 0},
	{logo: 0},
	{TimelineController: 0},
	{intro: 0},
	{blockLineA: 0},
	{blockLineB: 0},
	{checkPointA: 0},
	{checkPointB: 0},
	{collCheckCount: 0},
	{collCheckStop: 0},
	{GhostLineA: 0},
	{GhostLineB: 0},
	{pinned: 0},
	{ab: 0},
	{pin: 0},
	{points: 0},
	{aX: 0},
	{aY: 0},
	{bX: 0},
	{bY: 0},
	{selected: 0},
	{ids: 0},
	{line: 0},
	{lineA: 0},
	{lineB: 0},
	{rope: 0},
	{ropeA: 0},
	{ropeB: 0},
	{stopA: 0},
	{stopB: 0},
	{Sine: 0},
	{Game_Character: 0},
	{pinsCount: 0},
	{textCollCheckOver: 0},
	{wait: 0},
	{textWin: 0},
	{updownPanel: 0},
	{winCrown: 0},
	{winPanel: 0},
	{winParticl: 0},
	{winRay: 0},
	{Sprite: 0},
	{bg: 0},
	{gameboard: 0},
	{targetArt: 0},
	{winBG: 0},
	{Audio: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{start: 0},
	{waitTouch: 0},
	{hintOrder: 0},
	{touchPos: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{EndX: 0},
	{EndY: 0},
	{hintTouch: 0},
	{hide: 0},
	{idstwo: 0},
	{hintLines: 0},
	{hintButtons: 0},
	{AJAX: 0},
	{JSON: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_installgamebutton: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_separater: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_white_back: 0},
	{Fireflies: 0},
	{Bullet: 0},
	{Wrap: 0},
	{monkey: 0},
	{power: 0},
	{story_bg: 0},
	{Story_Boy: 0},
	{ScrollTo: 0},
	{story_Cam: 0},
	{story_fade: 0},
	{Story_Monk: 0},
	{Game_title_1: 0},
	{Game_title_2: 0},
	{Menu_character: 0},
	{Menu_ray: 0},
	{Menu_platfrom: 0},
	{Menu_Tree: 0},
	{GAMELAUNCHER: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{Anchor: 0},
	{Skip_btn: 0},
	{famLineAB: 0},
	{famBlockLine: 0},
	{OutPosLayout: 0},
	{GhostLines: 0},
	{saveload: 0},
	{level: 0}
];

self.InstanceType = {
	button: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	logo: class extends self.IWorldInstance {},
	TimelineController: class extends self.IInstance {},
	intro: class extends self.IWorldInstance {},
	blockLineA: class extends self.ISpriteInstance {},
	blockLineB: class extends self.ISpriteInstance {},
	checkPointA: class extends self.ISpriteInstance {},
	checkPointB: class extends self.ISpriteInstance {},
	collCheckCount: class extends self.ISpriteInstance {},
	collCheckStop: class extends self.ISpriteInstance {},
	GhostLineA: class extends self.ISpriteInstance {},
	GhostLineB: class extends self.ISpriteInstance {},
	pin: class extends self.ISpriteInstance {},
	points: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	lineA: class extends self.ISpriteInstance {},
	lineB: class extends self.ISpriteInstance {},
	rope: class extends self.ITiledBackgroundInstance {},
	ropeA: class extends self.ITiledBackgroundInstance {},
	ropeB: class extends self.ITiledBackgroundInstance {},
	stopA: class extends self.ISpriteInstance {},
	stopB: class extends self.ISpriteInstance {},
	Game_Character: class extends self.ISpriteInstance {},
	textCollCheckOver: class extends self.ITextInstance {},
	textWin: class extends self.ITextInstance {},
	updownPanel: class extends self.ISpriteInstance {},
	winCrown: class extends self.ISpriteInstance {},
	winPanel: class extends self.ISpriteInstance {},
	winParticl: class extends self.IParticlesInstance {},
	winRay: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	gameboard: class extends self.ISpriteInstance {},
	targetArt: class extends self.ISpriteInstance {},
	winBG: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	touchPos: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	hintTouch: class extends self.ISpriteInstance {},
	hintLines: class extends self.ITiledBackgroundInstance {},
	hintButtons: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	monkey: class extends self.ISpriteInstance {},
	power: class extends self.ISpriteInstance {},
	story_bg: class extends self.ISpriteInstance {},
	Story_Boy: class extends self.ISpriteInstance {},
	story_Cam: class extends self.ISpriteInstance {},
	story_fade: class extends self.ISpriteInstance {},
	Story_Monk: class extends self.ISpriteInstance {},
	Game_title_1: class extends self.ISpriteInstance {},
	Game_title_2: class extends self.ISpriteInstance {},
	Menu_character: class extends self.ISpriteInstance {},
	Menu_ray: class extends self.ISpriteInstance {},
	Menu_platfrom: class extends self.ISpriteInstance {},
	Menu_Tree: class extends self.ISpriteInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	Skip_btn: class extends self.ISpriteInstance {},
	famLineAB: class extends self.ISpriteInstance {},
	famBlockLine: class extends self.ISpriteInstance {},
	OutPosLayout: class extends self.ISpriteInstance {},
	GhostLines: class extends self.ISpriteInstance {}
}