const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.LOS,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.Game_Event76_Act17,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{f: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{back_btnasset: 0},
	{bg_ylw: 0},
	{next_btnasset: 0},
	{tutorial: 0},
	{Sine: 0},
	{tutorial_btn: 0},
	{bg: 0},
	{btnhelper: 0},
	{btnhelper2: 0},
	{Tween: 0},
	{button: 0},
	{hslvalue: 0},
	{check: 0},
	{coin: 0},
	{ScrollTo: 0},
	{destination: 0},
	{endblast: 0},
	{fader: 0},
	{endfade: 0},
	{endscreen: 0},
	{fade: 0},
	{home: 0},
	{home2: 0},
	{parent: 0},
	{laser: 0},
	{levelcounter: 0},
	{levelbtn: 0},
	{levelcompleted: 0},
	{levelendbg: 0},
	{leveltxt: 0},
	{leveltxtmenu: 0},
	{Fade: 0},
	{leveltxtmenu2: 0},
	{menu_btnasset: 0},
	{menubg: 0},
	{MFADE: 0},
	{initialAngle: 0},
	{Solid: 0},
	{DragDrop: 0},
	{mirror: 0},
	{nextshop: 0},
	{outline: 0},
	{Particles: 0},
	{prevshop: 0},
	{restart: 0},
	{restart2: 0},
	{shop: 0},
	{number: 0},
	{shopbg: 0},
	{soundbtn: 0},
	{LineOfSight: 0},
	{source: 0},
	{sourcepower: 0},
	{spark: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{st_text: 0},
	{framecounter: 0},
	{starunlocked: 0},
	{title: 0},
	{transitionfader: 0},
	{wbg: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{Browser: 0},
	{skip_btn: 0},
	{epsilon: 0},
	{nx: 0},
	{ny: 0},
	{bestT: 0},
	{x1: 0},
	{x2: 0},
	{y1: 0},
	{y2: 0},
	{hit: 0},
	{x3: 0},
	{y3: 0},
	{x4: 0},
	{y4: 0},
	{denom: 0},
	{t: 0},
	{s: 0},
	{ang: 0},
	{x: 0},
	{y: 0},
	{anglechecker: 0},
	{HSL: 0},
	{reached: 0},
	{layoutcounter: 0},
	{sound: 0},
	{completechecker: 0},
	{levelreached: 0},
	{x_offset: 0},
	{y_offset: 0},
	{counter: 0},
	{HSLlaser: 0},
	{bgframe: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	f: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	back_btnasset: class extends self.ISpriteInstance {},
	bg_ylw: class extends self.ISpriteInstance {},
	next_btnasset: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	tutorial_btn: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	btnhelper: class extends self.ISpriteInstance {},
	btnhelper2: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	destination: class extends self.ISpriteInstance {},
	endblast: class extends self.IParticlesInstance {},
	endfade: class extends self.ISpriteInstance {},
	endscreen: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	home2: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	levelbtn: class extends self.ISpriteInstance {},
	levelcompleted: class extends self.ISpriteInstance {},
	levelendbg: class extends self.ISpriteInstance {},
	leveltxt: class extends self.ITextInstance {},
	leveltxtmenu: class extends self.ITextInstance {},
	leveltxtmenu2: class extends self.ITextInstance {},
	menu_btnasset: class extends self.ISpriteInstance {},
	menubg: class extends self.ISpriteInstance {},
	MFADE: class extends self.ISpriteInstance {},
	mirror: class extends self.ISpriteInstance {},
	nextshop: class extends self.ISpriteInstance {},
	outline: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	prevshop: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	restart2: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	shopbg: class extends self.ISpriteInstance {},
	soundbtn: class extends self.ISpriteInstance {},
	source: class extends self.ISpriteInstance {},
	sourcepower: class extends self.ITiledBackgroundInstance {},
	spark: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	st_text: class extends self.ITextInstance {},
	starunlocked: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	transitionfader: class extends self.ISpriteInstance {},
	wbg: class extends self.ITiledBackgroundInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	skip_btn: class extends self.ITextInstance {}
}