const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.Browser,
		C3.Plugins.Json,
		C3.Plugins.Timeline,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Behaviors.Physics.Acts.RemoveJoints,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.JavaScriptInEvents.Gameevent_Event65_Act5,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{BlackPlaceNum: 0},
	{Physics: 0},
	{DragDrop: 0},
	{BlackPlaceRope: 0},
	{ButtonEffect: 0},
	{Tween: 0},
	{ButtonEffectMask: 0},
	{ButtonParticle: 0},
	{MoveTo: 0},
	{meat: 0},
	{Pin: 0},
	{CandyShadow: 0},
	{Rotate: 0},
	{CandyZone: 0},
	{Lion: 0},
	{ChainStart: 0},
	{ChainFinish: 0},
	{Chain1: 0},
	{Chain2: 0},
	{ChainParticles: 0},
	{GreenPlaceNum: 0},
	{GreenPlaceRope: 0},
	{HomeButton: 0},
	{Line: 0},
	{RestartButton: 0},
	{RopeStart: 0},
	{Rope1: 0},
	{RopeFinish: 0},
	{Rope2: 0},
	{SawNum: 0},
	{Saw: 0},
	{SawShadowNum: 0},
	{SawShadow: 0},
	{Sine: 0},
	{Star: 0},
	{StarGUI: 0},
	{StarsParticles: 0},
	{StarsParticles2: 0},
	{Fade: 0},
	{StartFade: 0},
	{SwipeEffect: 0},
	{WoodNum: 0},
	{Wood: 0},
	{WoodShadowNum: 0},
	{WoodShadow: 0},
	{Sine2: 0},
	{Babble: 0},
	{LoseFade: 0},
	{SwipeTrigger: 0},
	{WinFade: 0},
	{WinParcticles: 0},
	{WinParcticles2: 0},
	{WinParcticles3: 0},
	{BabbleParticles: 0},
	{BabbleParticles2: 0},
	{Finger: 0},
	{TutButton: 0},
	{WinnerTitle: 0},
	{Logo: 0},
	{Play: 0},
	{PlayEffect: 0},
	{playParticle: 0},
	{StartBackground: 0},
	{Gear: 0},
	{NoButton: 0},
	{TutReset: 0},
	{YesButton: 0},
	{Level: 0},
	{LevelPlace: 0},
	{LevelsTitle: 0},
	{LockParticle: 0},
	{MenuBackground: 0},
	{PlaceEffect: 0},
	{ReturnButton: 0},
	{TapPlaceEffect: 0},
	{TapPlaceEffectMask: 0},
	{Audio: 0},
	{Completed: 0},
	{LevelNumber: 0},
	{LevelNumber2: 0},
	{LocalStorage: 0},
	{TextLevel: 0},
	{TextLevel2: 0},
	{TextLevelShadow: 0},
	{TextLevelUnlocked: 0},
	{TextStarsCollected: 0},
	{TextStarsNeed: 0},
	{Touch: 0},
	{TextGoToStart: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{AJAX: 0},
	{Browser: 0},
	{JSON: 0},
	{TimelineController: 0},
	{Video: 0},
	{background_1: 0},
	{bg_: 0},
	{Bush: 0},
	{chain: 0},
	{Fade_outer: 0},
	{fade_spawner: 0},
	{Fireflies: 0},
	{fog: 0},
	{Menu_meat: 0},
	{Text_box: 0},
	{Tutorial_text: 0},
	{Uper_tree: 0},
	{water: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{AllRopes: 0},
	{AllChains: 0},
	{GUIButtons: 0},
	{LevelResetButtons: 0},
	{Levels: 0},
	{CompletedLevels: 0},
	{Lose: 0},
	{Win: 0},
	{SwipeX: 0},
	{SwipeY: 0},
	{Stars: 0},
	{InBabble: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	BlackPlaceRope: class extends self.ISpriteInstance {},
	ButtonEffect: class extends self.ISpriteInstance {},
	ButtonEffectMask: class extends self.ISpriteInstance {},
	ButtonParticle: class extends self.IParticlesInstance {},
	meat: class extends self.ISpriteInstance {},
	CandyShadow: class extends self.ISpriteInstance {},
	CandyZone: class extends self.ISpriteInstance {},
	Lion: class extends self.ISpriteInstance {},
	Chain1: class extends self.ISpriteInstance {},
	Chain2: class extends self.ISpriteInstance {},
	ChainParticles: class extends self.IParticlesInstance {},
	GreenPlaceRope: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	Rope1: class extends self.ISpriteInstance {},
	Rope2: class extends self.ISpriteInstance {},
	Saw: class extends self.ISpriteInstance {},
	SawShadow: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	StarGUI: class extends self.ISpriteInstance {},
	StarsParticles: class extends self.IParticlesInstance {},
	StarsParticles2: class extends self.IParticlesInstance {},
	StartFade: class extends self.ITiledBackgroundInstance {},
	SwipeEffect: class extends self.ISpriteInstance {},
	Wood: class extends self.ISpriteInstance {},
	WoodShadow: class extends self.ISpriteInstance {},
	Babble: class extends self.ISpriteInstance {},
	LoseFade: class extends self.ITiledBackgroundInstance {},
	SwipeTrigger: class extends self.ISpriteInstance {},
	WinFade: class extends self.ITiledBackgroundInstance {},
	WinParcticles: class extends self.IParticlesInstance {},
	WinParcticles2: class extends self.IParticlesInstance {},
	WinParcticles3: class extends self.IParticlesInstance {},
	BabbleParticles: class extends self.IParticlesInstance {},
	BabbleParticles2: class extends self.IParticlesInstance {},
	Finger: class extends self.ISpriteInstance {},
	TutButton: class extends self.ISpriteInstance {},
	WinnerTitle: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	PlayEffect: class extends self.ISpriteInstance {},
	playParticle: class extends self.IParticlesInstance {},
	StartBackground: class extends self.ITiledBackgroundInstance {},
	Gear: class extends self.ISpriteInstance {},
	NoButton: class extends self.ISpriteInstance {},
	TutReset: class extends self.ISpriteInstance {},
	YesButton: class extends self.ISpriteInstance {},
	LevelPlace: class extends self.ISpriteInstance {},
	LevelsTitle: class extends self.ISpriteInstance {},
	LockParticle: class extends self.IParticlesInstance {},
	MenuBackground: class extends self.ITiledBackgroundInstance {},
	PlaceEffect: class extends self.ISpriteInstance {},
	ReturnButton: class extends self.ISpriteInstance {},
	TapPlaceEffect: class extends self.ISpriteInstance {},
	TapPlaceEffectMask: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Completed: class extends self.ISpriteFontInstance {},
	LevelNumber: class extends self.ISpriteFontInstance {},
	LevelNumber2: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	TextLevel: class extends self.ISpriteFontInstance {},
	TextLevel2: class extends self.ISpriteFontInstance {},
	TextLevelShadow: class extends self.ISpriteFontInstance {},
	TextLevelUnlocked: class extends self.ISpriteFontInstance {},
	TextStarsCollected: class extends self.ISpriteFontInstance {},
	TextStarsNeed: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	TextGoToStart: class extends self.ISpriteFontInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	TimelineController: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	background_1: class extends self.ITiledBackgroundInstance {},
	bg_: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	chain: class extends self.ISpriteInstance {},
	Fade_outer: class extends self.ISpriteInstance {},
	fade_spawner: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	fog: class extends self.ITiledBackgroundInstance {},
	Menu_meat: class extends self.ISpriteInstance {},
	Text_box: class extends self.ISpriteInstance {},
	Tutorial_text: class extends self.ISpriteInstance {},
	Uper_tree: class extends self.ISpriteInstance {},
	water: class extends self.ITiledBackgroundInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	AllRopes: class extends self.ISpriteInstance {},
	AllChains: class extends self.ISpriteInstance {},
	GUIButtons: class extends self.ISpriteInstance {},
	LevelResetButtons: class extends self.ISpriteInstance {}
}