const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.NinePatch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.JavaScriptInEvents.EventSheet_Event107_Act1,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{"9patch": 0},
	{TileBox: 0},
	{DndPos: 0},
	{TopBar: 0},
	{Sprite2: 0},
	{Sine: 0},
	{TrashCan: 0},
	{Tiles: 0},
	{DragDrop: 0},
	{Flash: 0},
	{DnDColor: 0},
	{Matched: 0},
	{SColor: 0},
	{MColor: 0},
	{LColor: 0},
	{LRow: 0},
	{RRow: 0},
	{XRow: 0},
	{YRow: 0},
	{Check3: 0},
	{SCheck: 0},
	{FindRRow: 0},
	{FindLRow: 0},
	{FindXRow: 0},
	{FindYRow: 0},
	{Fade: 0},
	{Effects: 0},
	{Gbg: 0},
	{Anchor: 0},
	{TiledB: 0},
	{DndPos2: 0},
	{Tutorail: 0},
	{Loading: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Buttons: 0},
	{Text: 0},
	{GOverB: 0},
	{GameOver: 0},
	{Paused: 0},
	{SoundB: 0},
	{GameOver2: 0},
	{GameOver3: 0},
	{MusicB: 0},
	{Paused2: 0},
	{Sprite4: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{FindRow: 0},
	{Rings: 0},
	{Rows: 0},
	{Color: 0},
	{RandomDnD: 0},
	{HasRow: 0},
	{IfSpace: 0},
	{Score: 0},
	{ScoreA: 0},
	{Skip: 0},
	{HighScore: 0},
	{Music: 0},
	{Sound: 0},
	{DisE: 0}
];

self.InstanceType = {
	_9patch: class extends self.I9PatchInstance {},
	TileBox: class extends self.ISpriteInstance {},
	DndPos: class extends self.ISpriteInstance {},
	TopBar: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TrashCan: class extends self.ISpriteInstance {},
	Tiles: class extends self.ISpriteInstance {},
	DnDColor: class extends self.ISpriteInstance {},
	SColor: class extends self.ISpriteInstance {},
	MColor: class extends self.ISpriteInstance {},
	LColor: class extends self.ISpriteInstance {},
	LRow: class extends self.ISpriteInstance {},
	RRow: class extends self.ISpriteInstance {},
	XRow: class extends self.ISpriteInstance {},
	YRow: class extends self.ISpriteInstance {},
	Check3: class extends self.ISpriteInstance {},
	SCheck: class extends self.ISpriteInstance {},
	FindRRow: class extends self.ISpriteInstance {},
	FindLRow: class extends self.ISpriteInstance {},
	FindXRow: class extends self.ISpriteInstance {},
	FindYRow: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {},
	Gbg: class extends self.ISpriteInstance {},
	TiledB: class extends self.ITiledBackgroundInstance {},
	DndPos2: class extends self.ISpriteInstance {},
	Tutorail: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	GOverB: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	SoundB: class extends self.ISpriteInstance {},
	GameOver2: class extends self.ISpriteInstance {},
	GameOver3: class extends self.ISpriteInstance {},
	MusicB: class extends self.ISpriteInstance {},
	Paused2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Anchor: class extends self.ISpriteInstance {},
	FindRow: class extends self.ISpriteInstance {},
	Rings: class extends self.ISpriteInstance {},
	Rows: class extends self.ISpriteInstance {}
}