const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Browser,
		C3.Behaviors.wrap,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.time,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.JavaScriptInEvents.EventMain_Event41_Act14,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.EventMain_Event55_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.EventMain_Event69_Act8,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.EventMenu_Event1_Act4,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Behaviors.Fade.Cnds.OnWaitEnd,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Life: 0},
	{ID: 0},
	{enemy1: 0},
	{Flash: 0},
	{player: 0},
	{tower: 0},
	{btn_upDown: 0},
	{Touch: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{arrow_enemy: 0},
	{arrow_player: 0},
	{btn_attack: 0},
	{life_HUD: 0},
	{ScrollTo: 0},
	{background: 0},
	{base: 0},
	{enemy2: 0},
	{enemy3: 0},
	{SineSize: 0},
	{notice_result: 0},
	{btn_sound: 0},
	{Sine: 0},
	{title_image: 0},
	{Level: 0},
	{Fade: 0},
	{btn_level: 0},
	{table_levels: 0},
	{btn_play: 0},
	{LocalStorage: 0},
	{Sound: 0},
	{LevelCurrent: 0},
	{LimitY: 0},
	{btn_menu: 0},
	{notice_level: 0},
	{fade: 0},
	{tutorial: 0},
	{btn_start: 0},
	{logo: 0},
	{enemy4: 0},
	{enemy5: 0},
	{enemy6: 0},
	{Video: 0},
	{Browser: 0},
	{Sprite: 0},
	{flag: 0},
	{tree: 0},
	{log: 0},
	{Wrap: 0},
	{cloud: 0},
	{Particles: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Pin: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{Fadee: 0},
	{Enemy: 0},
	{Menu: 0},
	{EnemyCooldown: 0},
	{EnemyID: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0},
	{SplashScreen: 0},
	{LevelAvailable: 0},
	{NameOfLayout: 0}
];

self.InstanceType = {
	enemy1: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	tower: class extends self.ISpriteInstance {},
	btn_upDown: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	arrow_enemy: class extends self.ISpriteInstance {},
	arrow_player: class extends self.ISpriteInstance {},
	btn_attack: class extends self.ISpriteInstance {},
	life_HUD: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	enemy2: class extends self.ISpriteInstance {},
	enemy3: class extends self.ISpriteInstance {},
	notice_result: class extends self.ISpriteInstance {},
	btn_sound: class extends self.ISpriteInstance {},
	title_image: class extends self.ISpriteInstance {},
	btn_level: class extends self.ISpriteInstance {},
	table_levels: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Sound: class extends self.IInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	notice_level: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	btn_start: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	enemy4: class extends self.ISpriteInstance {},
	enemy5: class extends self.ISpriteInstance {},
	enemy6: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Browser: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	flag: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	log: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {},
	Fadee: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {}
}