const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Function,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.List,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.advert,
		C3.Plugins.Text,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.Gamesheet_Event128_Act2,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Exps.random,
		C3.Plugins.List.Acts.Remove,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Exps.AbsoluteY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Touch: 0},
	{xx: 0},
	{yy: 0},
	{MyX: 0},
	{MyY: 0},
	{flg: 0},
	{DistYToTouch: 0},
	{StartX: 0},
	{StartY: 0},
	{MinY: 0},
	{MaxY: 0},
	{TargetY: 0},
	{Letter: 0},
	{OnTheLine: 0},
	{CurY: 0},
	{Block: 0},
	{Function: 0},
	{Line: 0},
	{Pin: 0},
	{TxtBlock: 0},
	{Array: 0},
	{WordsList: 0},
	{Browser: 0},
	{List: 0},
	{TextBox: 0},
	{BtnAdd: 0},
	{DropList: 0},
	{BtnRandom: 0},
	{ADic: 0},
	{BtnDel: 0},
	{Array_First: 0},
	{Array_Shuffled: 0},
	{txtGenerated: 0},
	{BtnGenerate: 0},
	{BtnMusic: 0},
	{Sine: 0},
	{Title: 0},
	{BtnPlay: 0},
	{BtnSound: 0},
	{BtnInfo: 0},
	{Tween: 0},
	{BlackC: 0},
	{BtnClose: 0},
	{InfoBox: 0},
	{n: 0},
	{BtnLevel: 0},
	{txtBtnLevel: 0},
	{BtnBack: 0},
	{Sprite3: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{TxtLevel: 0},
	{BtnPause: 0},
	{BtnHome: 0},
	{PauseBox: 0},
	{BtnReset: 0},
	{BtnNext: 0},
	{LvCompleteBox: 0},
	{Line2: 0},
	{Arrow: 0},
	{PlatformInfo: 0},
	{MobileAdvert: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{Video: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{FBlock: 0},
	{FButtons: 0},
	{FPopups: 0},
	{SelectedBlock: 0},
	{BlockOnTheLine: 0},
	{Size: 0},
	{Word: 0},
	{Code: 0},
	{CodeGet: 0},
	{Level: 0},
	{Pause: 0},
	{LevelComplete: 0},
	{LevelStartTimer: 0},
	{CanvasTouchX: 0},
	{CanvasTouchY: 0},
	{MainWords: 0},
	{vLevel: 0},
	{vSound: 0},
	{vMusic: 0},
	{vPassedLevels: 0},
	{Type: 0},
	{Threes: 0},
	{Fours: 0},
	{Fives: 0},
	{Sixes: 0},
	{Sevens: 0},
	{TheCode: 0},
	{BiggestKey: 0},
	{ScaleValue: 0},
	{Txt: 0},
	{ShuffledTxt: 0},
	{pick: 0},
	{Info: 0},
	{Sound: 0},
	{Music: 0},
	{CamOn: 0},
	{DragScrollY: 0},
	{DragTouchY: 0},
	{DragTouchSpd: 0},
	{DragTouchDir: 0},
	{MaxTop: 0},
	{MinBottom: 0},
	{PassedLevels: 0},
	{Swipe: 0},
	{LevelSelectTimer: 0},
	{Dragging: 0},
	{AllLevels: 0},
	{AllLevelsN: 0},
	{ShowVideoAd: 0},
	{vLastX: 0},
	{vLastY: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	Block: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	TxtBlock: class extends self.ISpriteFontInstance {},
	Array: class extends self.IArrayInstance {},
	WordsList: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	List: class extends self.IListInstance {},
	TextBox: class extends self.ITextInputInstance {},
	BtnAdd: class extends self.IButtonInstance {},
	DropList: class extends self.IListInstance {},
	BtnRandom: class extends self.IButtonInstance {},
	ADic: class extends self.IDictionaryInstance {},
	BtnDel: class extends self.IButtonInstance {},
	Array_First: class extends self.IArrayInstance {},
	Array_Shuffled: class extends self.IArrayInstance {},
	txtGenerated: class extends self.ITextInputInstance {},
	BtnGenerate: class extends self.IButtonInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BlackC: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	InfoBox: class extends self.ISpriteInstance {},
	BtnLevel: class extends self.ISpriteInstance {},
	txtBtnLevel: class extends self.ISpriteFontInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TxtLevel: class extends self.ISpriteFontInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	PauseBox: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	LvCompleteBox: class extends self.ISpriteInstance {},
	Line2: class extends self.ITiledBackgroundInstance {},
	Arrow: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FPopups: class extends self.ISpriteInstance {}
}