const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.advert,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Dictionary,
		C3.Plugins.Function,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.lunarray_LiteTween.Acts.SetEasing,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.LocalStorage.Cnds.IsProcessingSets,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.Gamesheet_Event122_Act1,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Behaviors.lunarray_LiteTween.Acts.SetValue,
		C3.Behaviors.lunarray_LiteTween.Exps.Value,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.System.Exps.lowercase,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{MobileAdvert: 0},
	{num: 0},
	{flg: 0},
	{wordSID: 0},
	{frame: 0},
	{choose: 0},
	{select: 0},
	{words: 0},
	{Touch: 0},
	{Browser: 0},
	{posWord: 0},
	{board: 0},
	{wordWidth: 0},
	{frameNum: 0},
	{WordPID: 0},
	{match: 0},
	{wordP: 0},
	{Qustion: 0},
	{Dictionary: 0},
	{Function: 0},
	{alphabet: 0},
	{wordL: 0},
	{levelCode: 0},
	{generateBTN: 0},
	{Keyboard: 0},
	{QustionBox: 0},
	{clearBTN: 0},
	{LiteTween: 0},
	{popUp: 0},
	{Pin: 0},
	{nxtBTN: 0},
	{space: 0},
	{star: 0},
	{help: 0},
	{background: 0},
	{scoreBoard: 0},
	{menuBtn: 0},
	{leaf: 0},
	{homeBg: 0},
	{gameLogo: 0},
	{playBtn: 0},
	{Sine: 0},
	{rope: 0},
	{Sound: 0},
	{Share: 0},
	{About: 0},
	{Music: 0},
	{rope2: 0},
	{shrubBig: 0},
	{monkey: 0},
	{monkeysLeaf: 0},
	{monkeysHand: 0},
	{tial: 0},
	{bgPopUp: 0},
	{close: 0},
	{homeBtn: 0},
	{musicBtn: 0},
	{soundBtn: 0},
	{settingsTxt: 0},
	{Greattxt: 0},
	{starPlace: 0},
	{qustionSP: 0},
	{Array: 0},
	{levelSP: 0},
	{scoreSp: 0},
	{showWordSP: 0},
	{foundWordSP: 0},
	{foundWordBtn: 0},
	{popUpFoudWord: 0},
	{closeFindWordPop: 0},
	{LocalStorage: 0},
	{loading: 0},
	{move: 0},
	{size: 0},
	{guessWord: 0},
	{finnishTheGame: 0},
	{starFW: 0},
	{monkeysLeaf2: 0},
	{monkeysLeaf3: 0},
	{starFW2: 0},
	{Audio: 0},
	{movie: 0},
	{loadingSp: 0},
	{Video: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{fall: 0},
	{rotate: 0},
	{wordSF: 0},
	{wordPF: 0},
	{starPalceF: 0},
	{starF: 0},
	{menuF: 0},
	{helpNum: 0},
	{aalastUID: 0},
	{winVoice: 0},
	{levelStop: 0},
	{musicFrame: 0},
	{sound: 0},
	{waitStarFW: 0},
	{allWordsFound: 0},
	{waitLiteTween: 0},
	{stopLiteTween: 0},
	{NXT: 0},
	{guess: 0},
	{localLevel: 0},
	{localStarNum: 0},
	{foundCount: 0},
	{starFlag: 0},
	{popUpAngle: 0},
	{finalWordsTouched: 0},
	{matchPartOne: 0},
	{countMatch: 0},
	{found: 0},
	{starNum: 0},
	{foundWords: 0},
	{stop: 0},
	{between: 0},
	{matchAll: 0},
	{clickNum: 0},
	{counter: 0},
	{aalevelEnd: 0},
	{txt: 0},
	{Var: 0},
	{levelWord: 0},
	{levelData: 0},
	{level: 0},
	{lengh: 0},
	{Alphabet: 0},
	{finalNum: 0},
	{count: 0},
	{bool: 0},
	{levelWordL: 0},
	{frameNumbers: 0},
	{wordLUID: 0},
	{Type: 0},
	{Threes: 0},
	{Fours: 0},
	{Fives: 0},
	{Sixes: 0},
	{Sevens: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	MobileAdvert: class extends self.IInstance {},
	words: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	posWord: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	wordP: class extends self.ISpriteInstance {},
	Qustion: class extends self.ITextInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Function: class extends self.IInstance {},
	alphabet: class extends self.IDictionaryInstance {},
	wordL: class extends self.ISpriteInstance {},
	levelCode: class extends self.ITextInputInstance {},
	generateBTN: class extends self.IButtonInstance {},
	Keyboard: class extends self.IInstance {},
	QustionBox: class extends self.ITextInputInstance {},
	clearBTN: class extends self.IButtonInstance {},
	popUp: class extends self.ISpriteInstance {},
	nxtBTN: class extends self.ISpriteInstance {},
	space: class extends self.ISpriteInstance {},
	star: class extends self.ISpriteInstance {},
	help: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	scoreBoard: class extends self.ISpriteInstance {},
	menuBtn: class extends self.ISpriteInstance {},
	leaf: class extends self.ISpriteInstance {},
	homeBg: class extends self.ISpriteInstance {},
	gameLogo: class extends self.ISpriteInstance {},
	playBtn: class extends self.ISpriteInstance {},
	rope: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	Share: class extends self.ISpriteInstance {},
	About: class extends self.ISpriteInstance {},
	Music: class extends self.ISpriteInstance {},
	rope2: class extends self.ISpriteInstance {},
	shrubBig: class extends self.ISpriteInstance {},
	monkey: class extends self.ISpriteInstance {},
	monkeysLeaf: class extends self.ISpriteInstance {},
	monkeysHand: class extends self.ISpriteInstance {},
	tial: class extends self.ISpriteInstance {},
	bgPopUp: class extends self.ISpriteInstance {},
	close: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	musicBtn: class extends self.ISpriteInstance {},
	soundBtn: class extends self.ISpriteInstance {},
	settingsTxt: class extends self.ISpriteInstance {},
	Greattxt: class extends self.ISpriteInstance {},
	starPlace: class extends self.ISpriteInstance {},
	qustionSP: class extends self.ISpriteFontInstance {},
	Array: class extends self.IArrayInstance {},
	levelSP: class extends self.ISpriteFontInstance {},
	scoreSp: class extends self.ISpriteFontInstance {},
	showWordSP: class extends self.ISpriteFontInstance {},
	foundWordSP: class extends self.ISpriteFontInstance {},
	foundWordBtn: class extends self.ISpriteInstance {},
	popUpFoudWord: class extends self.ISpriteInstance {},
	closeFindWordPop: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	loading: class extends self.ISpriteInstance {},
	guessWord: class extends self.ISpriteFontInstance {},
	finnishTheGame: class extends self.ISpriteFontInstance {},
	starFW: class extends self.ISpriteInstance {},
	monkeysLeaf2: class extends self.ISpriteInstance {},
	monkeysLeaf3: class extends self.ISpriteInstance {},
	starFW2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	movie: class extends self.IDictionaryInstance {},
	loadingSp: class extends self.ISpriteFontInstance {},
	Video: class extends self.IWorldInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	wordSF: class extends self.ISpriteInstance {},
	wordPF: class extends self.ISpriteInstance {},
	starPalceF: class extends self.ISpriteInstance {},
	starF: class extends self.ISpriteInstance {},
	menuF: class extends self.ISpriteInstance {}
}