const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Pin,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Plugins.Keyboard,
		C3.Behaviors.Persist,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Behaviors.Turret,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Cnds.IsDoubleJumpEnabled,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.JavaScriptInEvents.Game_Event48_Act1,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{hero: 0},
	{Solid: 0},
	{wall: 0},
	{Jumpthru: 0},
	{move: 0},
	{rebuild: 0},
	{Pin: 0},
	{logo: 0},
	{id: 0},
	{key: 0},
	{Zone: 0},
	{trap: 0},
	{corpvs: 0},
	{TiledBackground: 0},
	{Sprite: 0},
	{Particles: 0},
	{Touch: 0},
	{LiteTween: 0},
	{door: 0},
	{Sprite5: 0},
	{trap02: 0},
	{Sprite7: 0},
	{Bullet: 0},
	{Fade: 0},
	{top: 0},
	{Sprite8: 0},
	{locked: 0},
	{Sprite9: 0},
	{SpriteFont: 0},
	{Sprite10: 0},
	{Keyboard: 0},
	{SpriteFont2: 0},
	{life: 0},
	{levelset: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Persist: 0},
	{Sprite13: 0},
	{Audio: 0},
	{trap01: 0},
	{Girar: 0},
	{Sprite16: 0},
	{Turret: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{SpriteFont3: 0},
	{Sprite19: 0},
	{Browser: 0},
	{Sprite21: 0},
	{Atrelar: 0},
	{hero2: 0},
	{TiledBackground2: 0},
	{Projétil: 0},
	{hero3: 0},
	{Sólido: 0},
	{esquerda: 0},
	{direita: 0},
	{key2: 0},
	{bloodui: 0},
	{trap03: 0},
	{Sprite14: 0},
	{key3: 0},
	{door2: 0},
	{trap04: 0},
	{ArmazenamentoLocal: 0},
	{Sprite2: 0},
	{tileset: 0},
	{Sine: 0},
	{tree: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{alltrap: 0},
	{game_pro: 0},
	{zone_width: 0},
	{zone_high: 0},
	{Parameter0: 0},
	{now_level: 0},
	{clean_level: 0}
];

self.InstanceType = {
	hero: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	move: class extends self.ISpriteInstance {},
	rebuild: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	key: class extends self.ISpriteInstance {},
	Zone: class extends self.IWorldInstance {},
	trap: class extends self.ISpriteInstance {},
	corpvs: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Touch: class extends self.IInstance {},
	door: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	trap02: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	top: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	levelset: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	trap01: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	hero2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	hero3: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	key2: class extends self.ISpriteInstance {},
	bloodui: class extends self.ISpriteInstance {},
	trap03: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	key3: class extends self.ISpriteInstance {},
	door2: class extends self.ISpriteInstance {},
	trap04: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	tileset: class extends self.ITiledBackgroundInstance {},
	tree: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	alltrap: class extends self.ISpriteInstance {}
}