const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.video,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.wrap,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Timeline,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportleft,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Game_sht_Event75_Act1,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.Game_sht_Event89_Act8,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.Start_sht_Event1_Act5,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.WaitForPreviousActions
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{logo: 0},
	{Touch: 0},
	{sky: 0},
	{TiledBackground2: 0},
	{Var: 0},
	{create: 0},
	{SCORE: 0},
	{Jumpthru: 0},
	{Platform: 0},
	{HIT: 0},
	{Enemi1: 0},
	{Enemi2: 0},
	{Enemi3: 0},
	{Enemi4: 0},
	{Enemi5: 0},
	{power: 0},
	{Player: 0},
	{Bullet: 0},
	{Player_bullet: 0},
	{HOME: 0},
	{jump: 0},
	{Moregamesbtn: 0},
	{PAUSE: 0},
	{Replay: 0},
	{Sine: 0},
	{START: 0},
	{BulletBar: 0},
	{BulletBox: 0},
	{SHOOT: 0},
	{flash: 0},
	{shoot: 0},
	{adl_back: 0},
	{adl_blocker: 0},
	{adl_separater: 0},
	{Wrap: 0},
	{CL: 0},
	{Obstacle: 0},
	{Particles: 0},
	{Smock: 0},
	{stones: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_white_back: 0},
	{LiteTween: 0},
	{DARK: 0},
	{Sprite4: 0},
	{POSITION: 0},
	{Solid: 0},
	{TiledBackground: 0},
	{adl_installgamebutton: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_Text2: 0},
	{adl_update_available: 0},
	{adl_update_button: 0},
	{v: 0},
	{adl_version_shower: 0},
	{OBJECTS: 0},
	{SpriteFont: 0},
	{Fichier2: 0},
	{fadein: 0},
	{fadeout: 0},
	{middle_fade: 0},
	{skip: 0},
	{st_text: 0},
	{story_bg: 0},
	{story_cloud: 0},
	{story_enemy: 0},
	{story_enemy2: 0},
	{story_player: 0},
	{story_tree: 0},
	{text_paper: 0},
	{TimelineController: 0},
	{bg_ylw: 0},
	{tutorial: 0},
	{next_btnasset: 0},
	{menu_btnasset: 0},
	{back_btnasset: 0},
	{tutorial_btn: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Fadee: 0},
	{Pin: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{Flash: 0},
	{Enemies: 0},
	{LiteTween2: 0},
	{GUI: 0},
	{PLAYERS: 0},
	{CONTROL: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0},
	{Bullet2: 0},
	{LAYOUT: 0},
	{HIGH_SCORE: 0},
	{MONSTER: 0},
	{MinScroll: 0},
	{inter: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	logo: class extends self.IWorldInstance {},
	Touch: class extends self.IInstance {},
	sky: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Platform: class extends self.ISpriteInstance {},
	Enemi1: class extends self.ISpriteInstance {},
	Enemi2: class extends self.ISpriteInstance {},
	Enemi3: class extends self.ISpriteInstance {},
	Enemi4: class extends self.ISpriteInstance {},
	Enemi5: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Player_bullet: class extends self.ISpriteInstance {},
	HOME: class extends self.ISpriteInstance {},
	jump: class extends self.ISpriteInstance {},
	Moregamesbtn: class extends self.ISpriteInstance {},
	PAUSE: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	START: class extends self.ISpriteInstance {},
	BulletBar: class extends self.ISpriteInstance {},
	BulletBox: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	shoot: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	CL: class extends self.ISpriteInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Smock: class extends self.ISpriteInstance {},
	stones: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	DARK: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Fichier2: class extends self.ISpriteInstance {},
	fadein: class extends self.ISpriteInstance {},
	fadeout: class extends self.ISpriteInstance {},
	middle_fade: class extends self.ISpriteInstance {},
	skip: class extends self.ISpriteInstance {},
	st_text: class extends self.ITextInstance {},
	story_bg: class extends self.ISpriteInstance {},
	story_cloud: class extends self.ISpriteInstance {},
	story_enemy: class extends self.ISpriteInstance {},
	story_enemy2: class extends self.ISpriteInstance {},
	story_player: class extends self.ISpriteInstance {},
	story_tree: class extends self.ISpriteInstance {},
	text_paper: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	bg_ylw: class extends self.ISpriteInstance {},
	tutorial: class extends self.ISpriteInstance {},
	next_btnasset: class extends self.ISpriteInstance {},
	menu_btnasset: class extends self.ISpriteInstance {},
	back_btnasset: class extends self.ISpriteInstance {},
	tutorial_btn: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Fadee: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	GUI: class extends self.ISpriteInstance {},
	PLAYERS: class extends self.ISpriteInstance {},
	CONTROL: class extends self.ISpriteInstance {}
}