const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.TextBox,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.List,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.advert,
		C3.Plugins.PlatformInfo,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.video,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.List.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.List.Acts.Select,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.JavaScriptInEvents.Gamesheet_Event92_Act2,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.PickNth,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Function.Exps.Param,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{n: 0},
	{T: 0},
	{B: 0},
	{R: 0},
	{L: 0},
	{RLTB: 0},
	{Prev: 0},
	{Next: 0},
	{Block: 0},
	{Fill: 0},
	{MyX: 0},
	{MyY: 0},
	{xx: 0},
	{yy: 0},
	{Path: 0},
	{Touch: 0},
	{Function: 0},
	{Line: 0},
	{Cam: 0},
	{TextBox: 0},
	{TxtLabelsf: 0},
	{BtnApply: 0},
	{List: 0},
	{BtnGenerate: 0},
	{TbxGenerate: 0},
	{Tween: 0},
	{BlackC: 0},
	{w: 0},
	{h: 0},
	{BtnHome: 0},
	{BtnReset: 0},
	{BtnMusic: 0},
	{txtLevel: 0},
	{Array: 0},
	{BtnPlay: 0},
	{txtTitle: 0},
	{MainNum: 0},
	{ShowNum: 0},
	{frame: 0},
	{BtnMiniBox: 0},
	{BtnBack: 0},
	{BtnBox: 0},
	{parent: 0},
	{txtLabel: 0},
	{txtLabel2: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Browser: 0},
	{BtnRandom: 0},
	{Hand: 0},
	{MobileAdvert: 0},
	{PlatformInfo: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{Sine: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{TiledBackground2: 0},
	{Rotate: 0},
	{Sprite5: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{Video: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{hgfjhgfjhgj: 0},
	{loader_gl_logo: 0},
	{loading_text: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{loading_text_percent: 0},
	{GAMELAUNCHER: 0},
	{FBlock: 0},
	{FPath: 0},
	{FLine: 0},
	{FButtons: 0},
	{RndCount: 0},
	{LastUID: 0},
	{LastX: 0},
	{LastY: 0},
	{GlobalN: 0},
	{Size: 0},
	{SizeCache: 0},
	{UsedRandom: 0},
	{Code: 0},
	{GetCode: 0},
	{LevelComplete: 0},
	{BlackTarget: 0},
	{nnn: 0},
	{Tutorials: 0},
	{TutStep: 0},
	{AllLevels: 0},
	{Level: 0},
	{HighestLevel: 0},
	{Music: 0},
	{Interstitial_ID: 0},
	{InterstitialVideo_ID: 0},
	{ShowVideoAd: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Block: class extends self.ISpriteInstance {},
	Path: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Line: class extends self.ISpriteInstance {},
	Cam: class extends self.ISpriteInstance {},
	TextBox: class extends self.ITextInputInstance {},
	TxtLabelsf: class extends self.ITextInstance {},
	BtnApply: class extends self.IButtonInstance {},
	List: class extends self.IListInstance {},
	BtnGenerate: class extends self.IButtonInstance {},
	TbxGenerate: class extends self.ITextInputInstance {},
	BlackC: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	txtLevel: class extends self.ISpriteFontInstance {},
	Array: class extends self.IArrayInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	txtTitle: class extends self.ISpriteFontInstance {},
	BtnMiniBox: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnBox: class extends self.ISpriteInstance {},
	txtLabel: class extends self.ISpriteFontInstance {},
	txtLabel2: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnRandom: class extends self.IButtonInstance {},
	Hand: class extends self.ISpriteInstance {},
	MobileAdvert: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	hgfjhgfjhgj: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	FBlock: class extends self.ISpriteInstance {},
	FPath: class extends self.ISpriteInstance {},
	FLine: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {}
}