const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Plugins.Touch,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.EightDir,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.video,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Exps.Gravity,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.TiledBg.Cnds.IsOutsideLayout,
		C3.Plugins.TiledBg.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.JavaScriptInEvents.Levels_Event140_Act2,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.JavaScriptInEvents.Levels_Event164_Act2,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.JavaScriptInEvents.Levels_Event182_Act8,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.Start_Event1_Act7,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Tilemap.Cnds.CompareX,
		C3.Plugins.Tilemap.Acts.SetX,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnReverseEnd,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{gravity: 0},
	{over: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Rabbit: 0},
	{Solid: 0},
	{T_floor: 0},
	{Keyboard: 0},
	{Tilemap: 0},
	{Touch: 0},
	{Background: 0},
	{mountain: 0},
	{saw: 0},
	{Forks: 0},
	{BOX1: 0},
	{BOX2: 0},
	{Forks2: 0},
	{ATTACK: 0},
	{Monster2: 0},
	{LiteTween: 0},
	{Sine: 0},
	{spider: 0},
	{Bullet: 0},
	{snowball: 0},
	{trees: 0},
	{ROCKET: 0},
	{"8Direction": 0},
	{plane: 0},
	{camera: 0},
	{Var: 0},
	{rocket: 0},
	{objects_destroy: 0},
	{ATTACK_start: 0},
	{Fade: 0},
	{dark: 0},
	{end: 0},
	{Tilemap2: 0},
	{guillotine: 0},
	{START: 0},
	{Gourdin: 0},
	{screw: 0},
	{Forks3: 0},
	{floor_down: 0},
	{saw2: 0},
	{spring: 0},
	{Golem: 0},
	{Monster1: 0},
	{RUN: 0},
	{ball: 0},
	{Golem2: 0},
	{ang: 0},
	{grey_brick: 0},
	{brick: 0},
	{snowball2: 0},
	{Text: 0},
	{CNTRL: 0},
	{PLAY: 0},
	{tittle: 0},
	{auto_jump: 0},
	{auto_SLIDE: 0},
	{Tilemap3: 0},
	{AID_POPUP: 0},
	{NEXT: 0},
	{PAUSE: 0},
	{REPLAY: 0},
	{setting: 0},
	{arrowsheet: 0},
	{sound: 0},
	{control: 0},
	{BACK: 0},
	{Head: 0},
	{LIFE: 0},
	{heart: 0},
	{sign2: 0},
	{tree2: 0},
	{CLOSE: 0},
	{sound_bar2: 0},
	{sound_bar: 0},
	{button: 0},
	{X1: 0},
	{X2: 0},
	{DragDrop: 0},
	{sound_button: 0},
	{sound_icon: 0},
	{Pin: 0},
	{sound_bar_mask: 0},
	{Audio: 0},
	{music_icon: 0},
	{Browser: 0},
	{moregamessheet: 0},
	{score: 0},
	{LocalStorage: 0},
	{Asset: 0},
	{fichier5sheet: 0},
	{yes: 0},
	{practice: 0},
	{TiledBackground: 0},
	{UP: 0},
	{clouds: 0},
	{Congratulations: 0},
	{flags: 0},
	{Asset2: 0},
	{CONTINUE: 0},
	{slide_sign: 0},
	{Spiky: 0},
	{FireBall: 0},
	{floor_down1: 0},
	{Fence: 0},
	{start: 0},
	{roting: 0},
	{Rotate: 0},
	{rock: 0},
	{red_brick: 0},
	{rock_jump: 0},
	{Smock: 0},
	{Diamond: 0},
	{Sprite: 0},
	{Video: 0},
	{AJAX: 0},
	{JSON: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_back: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{TiledBackground2: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Board: 0},
	{yes_btn: 0},
	{nobtn: 0},
	{OBSTACLES1: 0},
	{OBSTACLES2: 0},
	{Tilemaps: 0},
	{SAWS: 0},
	{POP: 0},
	{Flash: 0},
	{settings: 0},
	{Pin2: 0},
	{VOLUME: 0},
	{gameover: 0},
	{Y1: 0},
	{Y2: 0},
	{SCORE: 0},
	{SCORE_save: 0},
	{HIGHSCORE: 0},
	{LEVEL: 0},
	{Gamestart: 0},
	{reawrdedwatched: 0},
	{rewardedadvailable: 0},
	{more_games: 0},
	{AID: 0},
	{CONTROL: 0},
	{music: 0}
];

self.InstanceType = {
	Rabbit: class extends self.ISpriteInstance {},
	T_floor: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Touch: class extends self.IInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	mountain: class extends self.ITiledBackgroundInstance {},
	saw: class extends self.ISpriteInstance {},
	Forks: class extends self.ITiledBackgroundInstance {},
	BOX1: class extends self.ISpriteInstance {},
	BOX2: class extends self.ISpriteInstance {},
	Forks2: class extends self.ITiledBackgroundInstance {},
	Monster2: class extends self.ISpriteInstance {},
	spider: class extends self.ISpriteInstance {},
	snowball: class extends self.ISpriteInstance {},
	trees: class extends self.ISpriteInstance {},
	plane: class extends self.ISpriteInstance {},
	camera: class extends self.ITiledBackgroundInstance {},
	rocket: class extends self.ISpriteInstance {},
	objects_destroy: class extends self.ITiledBackgroundInstance {},
	ATTACK_start: class extends self.ITiledBackgroundInstance {},
	dark: class extends self.ITiledBackgroundInstance {},
	end: class extends self.ITiledBackgroundInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	guillotine: class extends self.ISpriteInstance {},
	Gourdin: class extends self.ISpriteInstance {},
	screw: class extends self.ISpriteInstance {},
	Forks3: class extends self.ITiledBackgroundInstance {},
	floor_down: class extends self.ITiledBackgroundInstance {},
	saw2: class extends self.ISpriteInstance {},
	spring: class extends self.ISpriteInstance {},
	Golem: class extends self.ISpriteInstance {},
	Monster1: class extends self.ISpriteInstance {},
	Golem2: class extends self.ISpriteInstance {},
	grey_brick: class extends self.ISpriteInstance {},
	brick: class extends self.ISpriteInstance {},
	snowball2: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	CNTRL: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	tittle: class extends self.ISpriteInstance {},
	auto_jump: class extends self.ISpriteInstance {},
	auto_SLIDE: class extends self.ISpriteInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	AID_POPUP: class extends self.ISpriteInstance {},
	NEXT: class extends self.ISpriteInstance {},
	PAUSE: class extends self.ISpriteInstance {},
	REPLAY: class extends self.ISpriteInstance {},
	setting: class extends self.ISpriteInstance {},
	arrowsheet: class extends self.ISpriteInstance {},
	sound: class extends self.ISpriteInstance {},
	control: class extends self.ISpriteInstance {},
	BACK: class extends self.ISpriteInstance {},
	Head: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	sign2: class extends self.ISpriteInstance {},
	tree2: class extends self.ISpriteInstance {},
	CLOSE: class extends self.ISpriteInstance {},
	sound_bar2: class extends self.ISpriteInstance {},
	sound_bar: class extends self.ISpriteInstance {},
	sound_button: class extends self.ISpriteInstance {},
	sound_icon: class extends self.ISpriteInstance {},
	sound_bar_mask: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	music_icon: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	moregamessheet: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	Asset: class extends self.ISpriteInstance {},
	fichier5sheet: class extends self.ISpriteInstance {},
	yes: class extends self.ISpriteInstance {},
	practice: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	UP: class extends self.ISpriteInstance {},
	clouds: class extends self.ISpriteInstance {},
	Congratulations: class extends self.ISpriteInstance {},
	flags: class extends self.ITiledBackgroundInstance {},
	Asset2: class extends self.ISpriteInstance {},
	CONTINUE: class extends self.ISpriteInstance {},
	slide_sign: class extends self.ISpriteInstance {},
	Spiky: class extends self.ISpriteInstance {},
	FireBall: class extends self.ISpriteInstance {},
	floor_down1: class extends self.ISpriteInstance {},
	Fence: class extends self.ITiledBackgroundInstance {},
	rock: class extends self.ISpriteInstance {},
	red_brick: class extends self.ISpriteInstance {},
	rock_jump: class extends self.ISpriteInstance {},
	Smock: class extends self.ISpriteInstance {},
	Diamond: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Fade: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	yes_btn: class extends self.ISpriteInstance {},
	nobtn: class extends self.ISpriteInstance {},
	OBSTACLES1: class extends self.ISpriteInstance {},
	OBSTACLES2: class extends self.ITiledBackgroundInstance {},
	Tilemaps: class extends self.ITilemapInstance {},
	SAWS: class extends self.ISpriteInstance {},
	POP: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	VOLUME: class extends self.ISpriteInstance {}
}