const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.video,
		C3.Plugins.XML,
		C3.Plugins.Json,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Events_game_Event65_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{button_info_again: 0},
	{button_info_levels: 0},
	{button_info_play: 0},
	{background_info: 0},
	{button_info_pause: 0},
	{button_info_sound: 0},
	{Fade: 0},
	{font_info_level: 0},
	{background_layout: 0},
	{button_home_continue: 0},
	{button_home_start: 0},
	{Sine: 0},
	{logo_home: 0},
	{level: 0},
	{button_level: 0},
	{button_level_font: 0},
	{background_layout_levels: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{motion_open: 0},
	{door_left: 0},
	{gold_coin: 0},
	{Solid: 0},
	{ground: 0},
	{isla_a: 0},
	{isla_b: 0},
	{isla_time: 0},
	{isla_big: 0},
	{sky: 0},
	{wall_vertical_big: 0},
	{wall_horizontal: 0},
	{wall_vertical: 0},
	{thorn: 0},
	{totem: 0},
	{door_right: 0},
	{door_down: 0},
	{tree: 0},
	{Bullet: 0},
	{effect_blow: 0},
	{effect_gold: 0},
	{Rotate: 0},
	{effect_smoke: 0},
	{effect_smoke_isla: 0},
	{Platform: 0},
	{ninja: 0},
	{ScrollTo: 0},
	{z_element_cam: 0},
	{z_element_door: 0},
	{z_element_ninja: 0},
	{z_element_isla: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{Video: 0},
	{XML: 0},
	{Sprite: 0},
	{JSON: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_back: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{logo_Gl: 0},
	{loader_bg: 0},
	{loader_gl_logo: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{islas: 0},
	{walls_horizontal: 0},
	{walls_vertical: 0},
	{golds: 0},
	{thorns: 0},
	{game: 0},
	{game_pre_start: 0},
	{game_next_level: 0},
	{game_level_now: 0},
	{gameplay_life: 0},
	{gameplay_jump: 0},
	{gameplay_direction: 0},
	{gameplay_collision_count: 0},
	{level_status_1: 0},
	{level_status_2: 0},
	{level_status_3: 0},
	{level_status_4: 0},
	{level_status_5: 0},
	{level_status_6: 0},
	{level_status_7: 0},
	{level_status_8: 0},
	{level_status_9: 0},
	{level_status_10: 0},
	{level_status_11: 0},
	{level_status_12: 0},
	{level_status_13: 0},
	{level_status_14: 0},
	{level_status_15: 0},
	{level_status_16: 0},
	{level_status_17: 0},
	{level_status_18: 0},
	{level_status_19: 0},
	{level_status_20: 0},
	{level_status_21: 0},
	{level_status_22: 0},
	{level_status_23: 0},
	{level_status_24: 0},
	{level_status_25: 0},
	{level_status_26: 0},
	{level_status_27: 0},
	{level_status_28: 0},
	{level_status_29: 0},
	{level_status_30: 0},
	{detect_mouse: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	button_info_again: class extends self.ISpriteInstance {},
	button_info_levels: class extends self.ISpriteInstance {},
	button_info_play: class extends self.ISpriteInstance {},
	background_info: class extends self.ISpriteInstance {},
	button_info_pause: class extends self.ISpriteInstance {},
	button_info_sound: class extends self.ISpriteInstance {},
	font_info_level: class extends self.ISpriteFontInstance {},
	background_layout: class extends self.ISpriteInstance {},
	button_home_continue: class extends self.ISpriteInstance {},
	button_home_start: class extends self.ISpriteInstance {},
	logo_home: class extends self.ISpriteInstance {},
	button_level: class extends self.ISpriteInstance {},
	button_level_font: class extends self.ISpriteFontInstance {},
	background_layout_levels: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	door_left: class extends self.ISpriteInstance {},
	gold_coin: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	isla_a: class extends self.ISpriteInstance {},
	isla_b: class extends self.ISpriteInstance {},
	isla_time: class extends self.ISpriteInstance {},
	isla_big: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	wall_vertical_big: class extends self.ISpriteInstance {},
	wall_horizontal: class extends self.ISpriteInstance {},
	wall_vertical: class extends self.ISpriteInstance {},
	thorn: class extends self.ISpriteInstance {},
	totem: class extends self.ISpriteInstance {},
	door_right: class extends self.ISpriteInstance {},
	door_down: class extends self.ISpriteInstance {},
	tree: class extends self.ISpriteInstance {},
	effect_blow: class extends self.ISpriteInstance {},
	effect_gold: class extends self.ISpriteInstance {},
	effect_smoke: class extends self.ISpriteInstance {},
	effect_smoke_isla: class extends self.ISpriteInstance {},
	ninja: class extends self.ISpriteInstance {},
	z_element_cam: class extends self.ISpriteInstance {},
	z_element_door: class extends self.ISpriteInstance {},
	z_element_ninja: class extends self.ISpriteInstance {},
	z_element_isla: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	XML: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	JSON: class extends self.IJSONInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_back: class extends self.ISpriteInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	logo_Gl: class extends self.ISpriteInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loader_gl_logo: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	islas: class extends self.ISpriteInstance {},
	walls_horizontal: class extends self.ISpriteInstance {},
	walls_vertical: class extends self.ISpriteInstance {},
	golds: class extends self.ISpriteInstance {},
	thorns: class extends self.ISpriteInstance {}
}